version: "2"
services:
    nginx:
      build:
          context: "./nginx"
      ports:
          - "80:80"
      links:
          - backing
          - thingaggregate
          - actor
          - geolocation
          - storagefacility
          - auth

    db:
        image: kpmeen/oracle-12c:full_monty
        shm_size: 4G
        ports:
          - "1521:1521"

    backing:
        build:
          context: "../../backing"
        environment:
          - CLIENT_ID
          - CLIENT_SECRET
          - CALLBACK_URL
          - JWT_SECRET
        ports:
          - "8080:8080"

    thingaggregate:
        image: musit_service_thing_aggregate:0.1-SNAPSHOT
        ports:
          - "7070:7070"
        environment:
          - MUSIT_SECURITY_MODULE
          - DATAPORTEN_CLIENT_ID
          - DATAPORTEN_CLIENT_SECRET
          - APPLICATION_SECRET
          - EVOLUTION_ENABLED
          - SLICK_DRIVER
          - SLICK_DB_DRIVER
          - SLICK_DB_URL
          - SLICK_DB_USER
          - SLICK_DB_PASSWORD
        links:
          - db

    actor:
        image: musit_service_actor:0.1-SNAPSHOT
        ports:
          - "7072:7070"
        environment:
          - MUSIT_SECURITY_MODULE
          - DATAPORTEN_CLIENT_ID
          - DATAPORTEN_CLIENT_SECRET
          - APPLICATION_SECRET
          - EVOLUTION_ENABLED
          - SLICK_DRIVER
          - SLICK_DB_DRIVER
          - SLICK_DB_URL
          - SLICK_DB_USER
          - SLICK_DB_PASSWORD
        links:
          - db

    geolocation:
        image: musit_service_geo_location:0.1-SNAPSHOT
        ports:
          - "7073:7070"
        environment:
          - MUSIT_SECURITY_MODULE
          - DATAPORTEN_CLIENT_ID
          - DATAPORTEN_CLIENT_SECRET
          - APPLICATION_SECRET

    auth:
        image: musit_service_auth:0.1-SNAPSHOT
        ports:
          - "7074:7070"
        environment:
          - MUSIT_SECURITY_MODULE
          - DATAPORTEN_CLIENT_ID
          - DATAPORTEN_CLIENT_SECRET
          - APPLICATION_SECRET
          - EVOLUTION_ENABLED
          - SLICK_DRIVER
          - SLICK_DB_DRIVER
          - SLICK_DB_URL
          - SLICK_DB_USER
          - SLICK_DB_PASSWORD
        links:
          - db
          - actor

    storagefacility:
        image: musit_service_storagefacility:0.1-SNAPSHOT
        ports:
          - "7075:7070"
        environment:
          - MUSIT_SECURITY_MODULE
          - DATAPORTEN_CLIENT_ID
          - DATAPORTEN_CLIENT_SECRET
          - APPLICATION_SECRET
          - EVOLUTION_ENABLED
          - SLICK_DRIVER
          - SLICK_DB_DRIVER
          - SLICK_DB_URL
          - SLICK_DB_USER
          - SLICK_DB_PASSWORD
        links:
          - db
