version: "2"
services:
    nginx:
        build:
            context: "./nginx"
        ports:
            - "80:80"
        links:
            - backing
            - webpack
    webpack:
        build:
            context: "../../frontend"
        volumes:
            - ../../frontend/src:/usr/src/app/src
            - ../../frontend/public:/usr/src/app/public
            - ../../fake_security.json:/usr/src/fake_security.json:ro
        environment:
          - PUBLIC_PORT=80
    backing:
        build:
          context: "../../backing"
        ports:
          - "3030:3030"
    db:
        image: postgres
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=postgres
        volumes:
          - ../../../postgres-storage:/var/lib/postgresql/data/
    thing:
        image: musit_service_musit_thing:0.1-SNAPSHOT
        environment:
          - APPLICATION_SECRET
    thingaggregate:
        image: musit_service_thing_aggregate:0.1-SNAPSHOT
        environment:
          - APPLICATION_SECRET
          - EVOLUTION_ENABLED
          - SLICK_DRIVER
          - SLICK_DB_DRIVER
          - SLICK_DB_URL
          - SLICK_DB_USER
          - SLICK_DB_PASSWORD
        links:
          - db
    core:
        image: musit_service_core:0.1-SNAPSHOT
        environment:
          - APPLICATION_SECRET
    storageadmin:
        image: musit_service_storage_admin:0.1-SNAPSHOT
        environment:
          - APPLICATION_SECRET
          - EVOLUTION_ENABLED
          - SLICK_DRIVER
          - SLICK_DB_DRIVER
          - SLICK_DB_URL
          - SLICK_DB_USER
          - SLICK_DB_PASSWORD
        links:
          - db
    actor:
        image: musit_service_actor:0.1-SNAPSHOT
        environment:
          - APPLICATION_SECRET
          - EVOLUTION_ENABLED
          - SLICK_DRIVER
          - SLICK_DB_DRIVER
          - SLICK_DB_URL
          - SLICK_DB_USER
          - SLICK_DB_PASSWORD
        links:
          - db
    geolocation:
        image: musit_service_geo_location:0.1-SNAPSHOT
        environment:
          - APPLICATION_SECRET
    event:
        image: musit_service_event:0.1-SNAPSHOT
        environment:
          - APPLICATION_SECRET
          - EVOLUTION_ENABLED
          - SLICK_DRIVER
          - SLICK_DB_DRIVER
          - SLICK_DB_URL
          - SLICK_DB_USER
          - SLICK_DB_PASSWORD
        links:
          - db
    time:
        image: musit_service_time:0.1-SNAPSHOT
        environment:
          - APPLICATION_SECRET
    storagefacility:
        image: musit_service_storagefacility:0.1-SNAPSHOT
        environment:
          - APPLICATION_SECRET="VEzE=puv#7-wUDeS@upr"
          - EVOLUTION_ENABLED=true
        links:
          - db
