version: "2"
services:
    nginx:
      build:
          context: "./nginx"
      ports:
          - "80:80"
      links:
          - backing
          - thingaggregate
          - actor
          - geolocation
          - storagefacility

    db:
        build: database/
        environment:
          - POSTGRES_USER
          - POSTGRES_PASSWORD
          - POSTGRES_DB
        volumes:
          - ../../../postgres-storage:/var/lib/postgresql/data/

    backing:
        build:
          context: "../../backing"
        ports:
          - "8080:8080"

    thingaggregate:
        image: musit_service_thing_aggregate:0.1-SNAPSHOT
        ports:
          - "7070:7070"
        environment:
          - APPLICATION_SECRET
          - EVOLUTION_ENABLED
          - SLICK_DRIVER
          - SLICK_DB_DRIVER
          - SLICK_DB_URL
          - SLICK_DB_USER
          - SLICK_DB_PASSWORD
        links:
          - db

    actor:
        image: musit_service_actor:0.1-SNAPSHOT
        ports:
          - "7072:7070"
        environment:
          - APPLICATION_SECRET
          - EVOLUTION_ENABLED
          - SLICK_DRIVER
          - SLICK_DB_DRIVER
          - SLICK_DB_URL
          - SLICK_DB_USER
          - SLICK_DB_PASSWORD
        links:
          - db

    geolocation:
        image: musit_service_geo_location:0.1-SNAPSHOT
        ports:
          - "7073:7070"
        environment:
          - APPLICATION_SECRET

    storagefacility:
        image: musit_service_storagefacility:0.1-SNAPSHOT
        ports:
          - "7075:7070"
        environment:
          - APPLICATION_SECRET
          - EVOLUTION_ENABLED
          - SLICK_DRIVER
          - SLICK_DB_DRIVER
          - SLICK_DB_URL
          - SLICK_DB_USER
          - SLICK_DB_PASSWORD
        links:
          - db
