version: "2"
services:
  nginx:
    build:
      context: "./nginx"
    ports:
      - "80:80"
    links:
      - backend
      - auth
      - barcode
      - document

  db:
    image: registry.gitlab.com/musit-norway/docker-oracle-12c:testdata
    shm_size: 4G
    ports:
      - "1521:1521"

  elasticsearch:
    image: registry.gitlab.com/musit-norway/docker-elasticsearch:latest
    ports:
      - 9200:9200

  postgres_db:
    build: postgres/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

    ports:
      - "5432:5432"

  postgres_db_person:
    image: harbor.uio.no/library/postgres
    #    build: postgres/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

    ports:
      - "5433:5432"

  backend:
    image: service_backend:0.1-SNAPSHOT
    ports:
      - "7072:7070"
    environment:
      - MUSIT_ENV
      - MUSIT_BASE_URL
      - DOCKER_HOSTNAME
      - MUSIT_SECURITY_MODULE
      - DATAPORTEN_CLIENT_ID
      - DATAPORTEN_CLIENT_SECRET
      - DATAPORTEN_SESSION_TIMEOUT
      - APPLICATION_SECRET
      - EVOLUTION_ENABLED
      - SLICK_DB_URL
      - SLICK_DB_USER
      - SLICK_DB_PASSWORD
      - ELASTICSEARCH_HOST
    links:
      - db
      - elasticsearch

  auth:
    image: service_auth:0.1-SNAPSHOT
    ports:
      - "7074:7070"
    environment:
      - MUSIT_ENV
      - MUSIT_BASE_URL
      - DOCKER_HOSTNAME
      - MUSIT_SECURITY_MODULE
      - CALLBACK_URL
      - DATAPORTEN_CLIENT_ID
      - DATAPORTEN_CLIENT_SECRET
      - DATAPORTEN_SESSION_TIMEOUT
      - APPLICATION_SECRET
      - EVOLUTION_ENABLED
      - SLICK_DB_URL
      - SLICK_DB_USER
      - SLICK_DB_PASSWORD
    links:
      - db

  barcode:
    image: service_barcode:0.1-SNAPSHOT
    ports:
      - "7076:7070"
    environment:
      - MUSIT_ENV
      - MUSIT_BASE_URL
      - DOCKER_HOSTNAME
      - MUSIT_SECURITY_MODULE
      - DATAPORTEN_CLIENT_ID
      - DATAPORTEN_CLIENT_SECRET
      - DATAPORTEN_SESSION_TIMEOUT
      - APPLICATION_SECRET
      - EVOLUTION_ENABLED
      - SLICK_DB_URL
      - SLICK_DB_USER
      - SLICK_DB_PASSWORD
    links:
      - db

  document:
    image: service_document:0.1-SNAPSHOT
    ports:
      - "7078:7070"
    environment:
      - MUSIT_ENV
      - MUSIT_BASE_URL
      - DOCKER_HOSTNAME
      - MUSIT_SECURITY_MODULE
      - DATAPORTEN_CLIENT_ID
      - DATAPORTEN_CLIENT_SECRET
      - DATAPORTEN_SESSION_TIMEOUT
      - APPLICATION_SECRET
      - EVOLUTION_ENABLED
      - SLICK_DB_URL
      - SLICK_DB_USER
      - SLICK_DB_PASSWORD
      # Props for the document management library to connect to postgres
      - SYMBIOTIC_POSTGRES_HOST
      - SYMBIOTIC_POSTGRES_PORT
      - SYMBIOTIC_POSTGRES_USE_SSL
      - SYMBIOTIC_DB_USER
      - SYMBIOTIC_DB_PASSWORD
      - SYMBIOTIC_DB_NAME
      - SYMBIOTIC_FS_ROOT_DIR
    links:
      - db
      - postgres_db
