version: "2"
services:
    db:
        build: database/
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=postgres
        volumes:
          - ../../../postgres-storage:/var/lib/postgresql/data/

    backing:
        build:
          context: "../../backing"
        ports:
          - "8080:8080"

    thingaggregate:
        image: musit_service_thing_aggregate:0.1-SNAPSHOT
        environment:
          - APPLICATION_SECRET=@ES^UzC^202_kBdV8VqJyW8`7lt7<5cQz`wEajYfJyS2_ThkE=Sr<tk4=s_DaPjC
        ports:
          - "7070:7070"
        environment:
          - APPLICATION_SECRET=@ES^UzC^202_kBdV8VqJyW8`7lt7<5cQz`wEajYfJyS2_ThkE=Sr<tk4=s_DaPjC
          - EVOLUTION_ENABLED
          - SLICK_DRIVER
          - SLICK_DB_DRIVER
          - SLICK_DB_URL
          - SLICK_DB_USER
          - SLICK_DB_PASSWORD
        links:
          - db

    actor:
        image: musit_service_actor:0.1-SNAPSHOT
        environment:
          - APPLICATION_SECRET=@ES^UzC^202_kBdV8VqJyW8`7lt7<5cQz`wEajYfJyS2_ThkE=Sr<tk4=s_DaPjC
        ports:
          - "7072:7070"
        environment:
          - APPLICATION_SECRET=@ES^UzC^202_kBdV8VqJyW8`7lt7<5cQz`wEajYfJyS2_ThkE=Sr<tk4=s_DaPjC
          - EVOLUTION_ENABLED
          - SLICK_DRIVER
          - SLICK_DB_DRIVER
          - SLICK_DB_URL
          - SLICK_DB_USER
          - SLICK_DB_PASSWORD
        links:
          - db

    geolocation:
        image: musit_service_geo_location:0.1-SNAPSHOT
        environment:
          - APPLICATION_SECRET=@ES^UzC^202_kBdV8VqJyW8`7lt7<5cQz`wEajYfJyS2_ThkE=Sr<tk4=s_DaPjC
        ports:
          - "7073:7070"
        environment:
          - APPLICATION_SECRET=@ES^UzC^202_kBdV8VqJyW8`7lt7<5cQz`wEajYfJyS2_ThkE=Sr<tk4=s_DaPjC
          - EVOLUTION_ENABLED
          - SLICK_DRIVER
          - SLICK_DB_DRIVER
          - SLICK_DB_URL
          - SLICK_DB_USER
          - SLICK_DB_PASSWORD
        links:
          - db

    storagefacility:
        image: musit_service_storagefacility:0.1-SNAPSHOT
        environment:
          - APPLICATION_SECRET="VEzE=puv#7-wUDeS@upr"
        ports:
          - "7075:7070"
        environment:
          - APPLICATION_SECRET=@ES^UzC^202_kBdV8VqJyW8`7lt7<5cQz`wEajYfJyS2_ThkE=Sr<tk4=s_DaPjC
          - EVOLUTION_ENABLED
          - SLICK_DRIVER
          - SLICK_DB_DRIVER
          - SLICK_DB_URL
          - SLICK_DB_USER
          - SLICK_DB_PASSWORD
        links:
          - db
