version: "2"
services:

    thingaggregate:
        image: musit_service_thing_aggregate:0.1-SNAPSHOT
        environment:
          - APPLICATION_SECRET=@ES^UzC^202_kBdV8VqJyW8`7lt7<5cQz`wEajYfJyS2_ThkE=Sr<tk4=s_DaPjC
        ports:
          - "7072:7070"

    storageadmin:
        image: musit_service_storage_admin:0.1-SNAPSHOT
        environment:
          - APPLICATION_SECRET=@ES^UzC^202_kBdV8VqJyW8`7lt7<5cQz`wEajYfJyS2_ThkE=Sr<tk4=s_DaPjC
        ports:
          - "7073:7070"

    actor:
        image: musit_service_actor:0.1-SNAPSHOT
        environment:
          - APPLICATION_SECRET=@ES^UzC^202_kBdV8VqJyW8`7lt7<5cQz`wEajYfJyS2_ThkE=Sr<tk4=s_DaPjC
        ports:
          - "7074:7070"

    geolocation:
        image: musit_service_geo_location:0.1-SNAPSHOT
        environment:
          - APPLICATION_SECRET=@ES^UzC^202_kBdV8VqJyW8`7lt7<5cQz`wEajYfJyS2_ThkE=Sr<tk4=s_DaPjC
        ports:
          - "7075:7070"

    event:
        image: musit_service_event:0.1-SNAPSHOT
        environment:
          - APPLICATION_SECRET=@ES^UzC^202_kBdV8VqJyW8`7lt7<5cQz`wEajYfJyS2_ThkE=Sr<tk4=s_DaPjC
        ports:
          - "7076:7070"

    storagefacility:
        image: musit_service_storagefacility:0.1-SNAPSHOT
        environment:
          - APPLICATION_SECRET="VEzE=puv#7-wUDeS@upr"
        ports:
          - "7077:7070"
