version: "2"
services:
  nginx:
    build:
      context: "./nginx"
    ports:
      - "80:80"
    links:
      - backend
      - auth
      - barcode

  db:
    image: registry.gitlab.com/musit-norway/docker-oracle-12c:testdata
    shm_size: 4G
    ports:
      - "1521:1521"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.3
    container_name: dev_elasticsearch
    environment:
      - cluster.name=musit-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ports:
      - 9200:9200

  backend:
    image: service_backend:0.1-SNAPSHOT
    ports:
      - "7072:7070"
    environment:
      - MUSIT_ENV
      - MUSIT_BASE_URL
      - DOCKER_HOSTNAME
      - MUSIT_SECURITY_MODULE
      - DATAPORTEN_CLIENT_ID
      - DATAPORTEN_CLIENT_SECRET
      - DATAPORTEN_SESSION_TIMEOUT
      - APPLICATION_SECRET
      - EVOLUTION_ENABLED
      - SLICK_DB_URL
      - SLICK_DB_USER
      - SLICK_DB_PASSWORD
    links:
      - db
      - elasticsearch

  auth:
    image: service_auth:0.1-SNAPSHOT
    ports:
      - "7074:7070"
    environment:
      - MUSIT_ENV
      - MUSIT_BASE_URL
      - DOCKER_HOSTNAME
      - MUSIT_SECURITY_MODULE
      - CALLBACK_URL
      - DATAPORTEN_CLIENT_ID
      - DATAPORTEN_CLIENT_SECRET
      - DATAPORTEN_SESSION_TIMEOUT
      - APPLICATION_SECRET
      - EVOLUTION_ENABLED
      - SLICK_DB_URL
      - SLICK_DB_USER
      - SLICK_DB_PASSWORD
    links:
      - db

  barcode:
    image: service_barcode:0.1-SNAPSHOT
    ports:
      - "7076:7070"
    environment:
      - MUSIT_ENV
      - MUSIT_BASE_URL
      - DOCKER_HOSTNAME
      - MUSIT_SECURITY_MODULE
      - DATAPORTEN_CLIENT_ID
      - DATAPORTEN_CLIENT_SECRET
      - DATAPORTEN_SESSION_TIMEOUT
      - APPLICATION_SECRET
      - EVOLUTION_ENABLED
      - SLICK_DB_URL
      - SLICK_DB_USER
      - SLICK_DB_PASSWORD
    links:
      - db
