version: "2"
services:
  nginx:
    build:
      context: "./nginx"
    ports:
      - "80:80"
    links:
      - thingaggregate
      - actor
      - geolocation
      - storagefacility
      - auth
      - barcode
      - management

  db:
    image: musitproject/oracle-12c:testdata
    shm_size: 4G
    ports:
      - "1521:1521"

  thingaggregate:
    image: service_thing_aggregate:0.1-SNAPSHOT
    ports:
      - "7070:7070"
    environment:
      - MUSIT_ENV
      - MUSIT_BASE_URL
      - DOCKER_HOSTNAME
      - MUSIT_SECURITY_MODULE
      - DATAPORTEN_CLIENT_ID
      - DATAPORTEN_CLIENT_SECRET
      - DATAPORTEN_SESSION_TIMEOUT
      - APPLICATION_SECRET
      - EVOLUTION_ENABLED
      - SLICK_DB_URL
      - SLICK_DB_USER
      - SLICK_DB_PASSWORD
    links:
      - db

  actor:
    image: service_actor:0.1-SNAPSHOT
    ports:
      - "7072:7070"
    environment:
      - MUSIT_ENV
      - MUSIT_BASE_URL
      - DOCKER_HOSTNAME
      - MUSIT_SECURITY_MODULE
      - DATAPORTEN_CLIENT_ID
      - DATAPORTEN_CLIENT_SECRET
      - DATAPORTEN_SESSION_TIMEOUT
      - APPLICATION_SECRET
      - EVOLUTION_ENABLED
      - SLICK_DB_URL
      - SLICK_DB_USER
      - SLICK_DB_PASSWORD
    links:
      - db

  geolocation:
    image: service_geo_location:0.1-SNAPSHOT
    ports:
      - "7073:7070"
    environment:
      - MUSIT_ENV
      - MUSIT_BASE_URL
      - DOCKER_HOSTNAME
      - MUSIT_SECURITY_MODULE
      - DATAPORTEN_CLIENT_ID
      - DATAPORTEN_CLIENT_SECRET
      - DATAPORTEN_SESSION_TIMEOUT
      - APPLICATION_SECRET
      - SLICK_DB_URL
      - SLICK_DB_USER
      - SLICK_DB_PASSWORD
    links:
      - db

  auth:
    image: service_auth:0.1-SNAPSHOT
    ports:
      - "7074:7070"
    environment:
      - MUSIT_ENV
      - MUSIT_BASE_URL
      - DOCKER_HOSTNAME
      - MUSIT_SECURITY_MODULE
      - CALLBACK_URL
      - DATAPORTEN_CLIENT_ID
      - DATAPORTEN_CLIENT_SECRET
      - DATAPORTEN_SESSION_TIMEOUT
      - APPLICATION_SECRET
      - EVOLUTION_ENABLED
      - SLICK_DB_URL
      - SLICK_DB_USER
      - SLICK_DB_PASSWORD
    links:
      - db

  storagefacility:
    image: service_storagefacility:0.1-SNAPSHOT
    ports:
      - "7075:7070"
    environment:
      - MUSIT_ENV
      - MUSIT_BASE_URL
      - DOCKER_HOSTNAME
      - MUSIT_SECURITY_MODULE
      - DATAPORTEN_CLIENT_ID
      - DATAPORTEN_CLIENT_SECRET
      - DATAPORTEN_SESSION_TIMEOUT
      - APPLICATION_SECRET
      - EVOLUTION_ENABLED
      - SLICK_DB_URL
      - SLICK_DB_USER
      - SLICK_DB_PASSWORD
    links:
      - db

  barcode:
    image: service_barcode:0.1-SNAPSHOT
    ports:
      - "7076:7070"
    environment:
      - MUSIT_ENV
      - MUSIT_BASE_URL
      - DOCKER_HOSTNAME
      - MUSIT_SECURITY_MODULE
      - DATAPORTEN_CLIENT_ID
      - DATAPORTEN_CLIENT_SECRET
      - DATAPORTEN_SESSION_TIMEOUT
      - APPLICATION_SECRET
      - EVOLUTION_ENABLED
      - SLICK_DB_URL
      - SLICK_DB_USER
      - SLICK_DB_PASSWORD
    links:
      - db

  management:
    image: service_management:0.1-SNAPSHOT
    ports:
      - "7077:7070"
    environment:
      - MUSIT_SECURITY_MODULE
      - DATAPORTEN_CLIENT_ID
      - DATAPORTEN_CLIENT_SECRET
      - DATAPORTEN_SESSION_TIMEOUT
      - APPLICATION_SECRET
      - EVOLUTION_ENABLED
      - SLICK_DB_URL
      - SLICK_DB_USER
      - SLICK_DB_PASSWORD
    links:
      - db
