######################################################################
# GitLab CI build script for the MUSIT backend project               #
######################################################################
image: $MUSIT_DOCKER_REGISTRY/musit/docker-scala-sbt

# -----
# Need to temporarily disable caches until we figure out how to properly do a
# cleanup of docker containers and images on the runner agent host machines.
# -----
# cache:
#  paths:
#    - $HOME/.sbt
#    - $HOME/.coursier

variables:
  DOCKER_DRIVER: overlay

services:
  - docker:dind

before_script:
  - echo "Running build $CI_BUILD_ID"
  - mkdir $HOME/.docker
  - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json
  - docker info

stages:
  - test
  - build

test:
  stage: test
  script:
    - echo "Building and running tests..."
    - sbt -mem 2048 scalastyle clean coverage test coverageReport
    # Check if the scalariform modified any files during the build. If yes, fail the build.
    - git status
    - git diff --exit-code || (echo "ERROR Scalariform check failed, see differences above."; false)
    # Aggregate the coverage report
    - sbt coverageAggregate
    # Do not publish coverage to codacy if the build is a PR from a forked repo.
    - if [[ -n "$CODACY_PROJECT_TOKEN" ]]; then sbt codacyCoverage; else echo "Coverage reporting disabled for PR from forks"; fi

build:
  stage: build
  script:
    - sbt docker:publish
  only:
    - master@MUSIT-Norway/musit
