import ObservationHeaderComponent from './ObservationHeaderComponent'
import ObservationDoubleTextAreaComponent from './ObservationDoubleTextAreaComponent'
import ObservationFromToNumberCommentComponent from './ObservationFromToNumberCommentComponent'

export { ObservationHeaderComponent, ObservationDoubleTextAreaComponent, ObservationFromToNumberCommentComponent }
