package models.analysis

import models.analysis.LeftoverSamples.LeftoverSample
import models.analysis.SampleStatuses.SampleStatus
import no.uio.musit.models.ObjectTypes.ObjectType
import no.uio.musit.models.{ActorId, MuseumId, ObjectUUID}
import org.joda.time.DateTime
import play.api.libs.json.{Format, Json, Reads}

case class SampleObject(
    objectId: Option[ObjectUUID],
    originatedObjectUuid: ObjectUUID,
    parentObjectId: Option[ObjectUUID],
    parentObjectType: ObjectType,
    isExtracted: Boolean,
    museumId: MuseumId,
    status: SampleStatus,
    responsible: Option[ActorId],
    createdDate: Option[DateTime],
    // TODO: Add auto generated sample ID
    sampleId: Option[String],
    externalId: Option[ExternalId],
    sampleTypeId: Option[SampleTypeId],
    size: Option[Size],
    container: Option[String],
    storageMedium: Option[String],
    treatment: Option[String],
    leftoverSample: LeftoverSample,
    description: Option[String],
    note: Option[String],
    registeredStamp: Option[ActorStamp],
    updatedStamp: Option[ActorStamp],
    isDeleted: Boolean
)

object SampleObject {

  implicit val format: Format[SampleObject] = Json.format[SampleObject]

}

case class SaveSampleObject(
    parentObjectId: Option[ObjectUUID],
    originatedObjectUuid: ObjectUUID,
    parentObjectType: ObjectType,
    isExtracted: Boolean,
    museumId: MuseumId,
    status: SampleStatus,
    responsible: Option[ActorId],
    createdDate: Option[DateTime],
    // TODO: Add autogenerated sample ID
    sampleId: Option[String],
    externalId: Option[ExternalId],
    sampleTypeId: Option[SampleTypeId],
    size: Option[Size],
    container: Option[String],
    storageMedium: Option[String],
    treatment: Option[String],
    leftoverSample: LeftoverSample,
    description: Option[String],
    note: Option[String]
) {

  def asSampleObject: SampleObject =
    SampleObject(
      objectId = None,
      originatedObjectUuid = originatedObjectUuid,
      parentObjectId = parentObjectId,
      parentObjectType = parentObjectType,
      isExtracted = isExtracted,
      museumId = museumId,
      status = status,
      responsible = responsible,
      createdDate = createdDate,
      sampleId = sampleId,
      externalId = externalId,
      sampleTypeId = sampleTypeId,
      size = size,
      container = container,
      storageMedium = storageMedium,
      treatment = treatment,
      leftoverSample = leftoverSample,
      description = description,
      note = note,
      registeredStamp = None,
      updatedStamp = None,
      isDeleted = false
    )

}

object SaveSampleObject {

  implicit val reads: Reads[SaveSampleObject] = Json.reads[SaveSampleObject]

}
