# --MUSARK_AUTH schema

# --- !Ups

CREATE SCHEMA IF NOT EXISTS MUSARK_AUTH;


CREATE TABLE MUSARK_AUTH.AUTH_GROUP (
  group_uuid        VARCHAR2(36) NOT NULL,
  group_name        VARCHAR(100) NOT NULL,
  group_permission  INTEGER      NOT NULL,
  group_museumId    INTEGER      NOT NULL,
  group_description VARCHAR(512),
  PRIMARY KEY (group_uuid),
  CONSTRAINT unique_group_name UNIQUE (group_name)
);

CREATE TABLE MUSARK_AUTH.MUSEUM_COLLECTION (
  collection_uuid               VARCHAR2(36) NOT NULL,
  collection_name               VARCHAR(100),
  collection_schema_identifiers VARCHAR(100) NOT NULL,
  PRIMARY KEY (collection_uuid),
  CONSTRAINT unique_mcol_name UNIQUE (collection_name)
);

CREATE TABLE MUSARK_AUTH.USER_AUTH_GROUP (
  uag_id           NUMBER(20) GENERATED BY DEFAULT AS IDENTITY,
  user_feide_email VARCHAR(254) NOT NULL,
  group_uuid       VARCHAR2(36) NOT NULL,
  collection_uuid  VARCHAR(36),
  PRIMARY KEY (uag_id),
  FOREIGN KEY (group_uuid) REFERENCES MUSARK_AUTH.AUTH_GROUP (group_uuid),
  FOREIGN KEY (collection_uuid) REFERENCES MUSARK_AUTH.MUSEUM_COLLECTION (collection_uuid),
  CONSTRAINT unique_auth_entry UNIQUE (user_feide_email, group_uuid, collection_uuid)
);

CREATE TABLE MUSARK_AUTH.USER_INFO (
  user_uuid    VARCHAR2(36) NOT NULL,
  secondary_id VARCHAR(512),
  name         VARCHAR(512),
  email        VARCHAR(254),
  picture      VARCHAR(100),
  PRIMARY KEY (user_uuid)
);

-- Table for keeping tabs on a users authenticated activity. "user_uuid" is not
-- set as a foreign key deliberately. This allows us to prepare the session with
-- a unique ID before we've received the access token from Dataporten.
CREATE TABLE MUSARK_AUTH.USER_SESSION (
  session_uuid     VARCHAR2(36)      NOT NULL,
  token            VARCHAR2(36),
  user_uuid        VARCHAR2(36),
  login_time       TIMESTAMP, -- WITH TIME ZONE,
  last_active      TIMESTAMP, -- WITH TIME ZONE,
  is_logged_in     INTEGER DEFAULT 0 NOT NULL,
  token_expires_in NUMBER(20),
  client           VARCHAR2(20),
  PRIMARY KEY (session_uuid)
);


# --- !Downs
