#
# TEST VERSION OF THE SCHEMA WITH relaxed PRIMARY AND FOREIGN KEY CONSTRAINTS
                                                  #
                                                  # STORAGE FACILITY SCHEMA
                                                  #
                                          # --- !Ups

                                          CREATE SCHEMA IF NOT EXISTS MUSARK_STORAGE;

-- ===========================================================================
-- Tables for storage nodes
-- ===========================================================================

CREATE TABLE MUSARK_STORAGE.STORAGE_NODE (
  storage_node_id   NUMBER(20) GENERATED BY DEFAULT AS IDENTITY,
  storage_node_uuid VARCHAR2(36)             NOT NULL,
  storage_node_name VARCHAR(512),
  area              NUMBER,
  area_to           NUMBER,
  is_storage_unit   VARCHAR(1)   DEFAULT '1',
  is_part_of        NUMBER(20),
  height            NUMBER,
  height_to         NUMBER,
  node_path         VARCHAR(1000)            NOT NULL,
  is_deleted        INTEGER DEFAULT 0        NOT NULL,
  storage_type      VARCHAR(100) DEFAULT 'StorageUnit',
  group_read        VARCHAR(4000),
  group_write       VARCHAR(4000),
  old_barcode       NUMBER(20),
  museum_id         INTEGER                  NOT NULL,
  updated_by        VARCHAR2(36)             NOT NULL,
  updated_date      TIMESTAMP                NOT NULL,
  PRIMARY KEY (storage_node_id)
);

CREATE TABLE MUSARK_STORAGE.ROOM (
  storage_node_id               NUMBER(20) NOT NULL,
  perimeter_security            INTEGER,
  theft_protection              INTEGER,
  fire_protection               INTEGER,
  water_damage_assessment       INTEGER,
  routines_and_contingency_plan INTEGER,
  relative_humidity             INTEGER,
  temperature_assessment        INTEGER,
  lighting_condition            INTEGER,
  preventive_conservation       INTEGER,
  PRIMARY KEY (storage_node_id),
  FOREIGN KEY (storage_node_id) REFERENCES MUSARK_STORAGE.STORAGE_NODE (storage_node_id)
);

CREATE TABLE MUSARK_STORAGE.BUILDING (
  storage_node_id NUMBER(20) NOT NULL,
  postal_address  VARCHAR(512),
  PRIMARY KEY (storage_node_id),
  FOREIGN KEY (storage_node_id) REFERENCES MUSARK_STORAGE.STORAGE_NODE (storage_node_id)
);

CREATE TABLE MUSARK_STORAGE.ORGANISATION (
  storage_node_id NUMBER(20) NOT NULL,
  postal_address  VARCHAR(512),
  PRIMARY KEY (storage_node_id),
  FOREIGN KEY (storage_node_id) REFERENCES MUSARK_STORAGE.STORAGE_NODE (storage_node_id)
);

-- ===========================================================================
-- The NEW event tables
-- ===========================================================================
CREATE SEQUENCE nevent_sequence
  INCREMENT BY 1
  START WITH 1
  NOMAXVALUE
  NOCYCLE
  NOCACHE;

CREATE TABLE MUSARK_STORAGE.NEW_EVENT (
  event_id        NUMBER(20) DEFAULT nevent_sequence.nextval,
  type_id         VARCHAR2(36) NOT NULL,
  museum_id       INTEGER,
  event_date      TIMESTAMP    NOT NULL,
  registered_by   VARCHAR2(36) NOT NULL,
  registered_date TIMESTAMP    NOT NULL,
  part_of         NUMBER(20),
  affected_uuid   VARCHAR2(36),
  affected_type   VARCHAR2(50), -- collection | sample | node | ...
  note            VARCHAR2(500),
  event_json      CLOB,
  PRIMARY KEY (event_id)
);

CREATE TABLE MUSARK_STORAGE.NEW_LOCAL_OBJECT (
  object_uuid         VARCHAR2(36) NOT NULL,
  latest_move_id      NUMBER(20)   NOT NULL,
  current_location_id VARCHAR2(36) NOT NULL,
  museum_id           INTEGER      NOT NULL,
  object_type         VARCHAR(50) DEFAULT 'collection', -- possible values can be 'collection', or 'sample'
  PRIMARY KEY (object_uuid)
  -- We do not enforce foreign key constraints here to make testing easier.
);

-- TODO: This table can be removed after migration is completed and
-- all API's have been updated to use the new backend code.
CREATE TABLE MUSARK_STORAGE.MIGRATED_EVENTS (
  old_event_id NUMBER(20) NOT NULL,
  PRIMARY KEY (old_event_id)
);

-- ===========================================================================
-- Event specific tables.
--
-- TODO: Remove once all events are migrated to new table structure!!!
-- ===========================================================================
CREATE TABLE MUSARK_STORAGE.ROLE (
  role_id   INTEGER GENERATED BY DEFAULT AS IDENTITY,
  name      VARCHAR2(100) NOT NULL,
  data_type VARCHAR2(100),
  PRIMARY KEY (role_id)
);

CREATE TABLE MUSARK_STORAGE.EVENT_TYPE (
  event_type_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  name          VARCHAR(100) NOT NULL,
  PRIMARY KEY (event_type_id)
);

-- The main table for storing events in the StorageFacility service.
CREATE TABLE MUSARK_STORAGE.EVENT (
  event_id        NUMBER(20) GENERATED BY DEFAULT AS IDENTITY,
  event_type_id   INTEGER      NOT NULL, -- Move to separate table if we want to allow multiple instantiations
  note            VARCHAR2(500),
  event_date      TIMESTAMP    NOT NULL, -- When the event happened. Should be nullable.
  registered_by   VARCHAR2(36) NOT NULL,
  registered_date TIMESTAMP    NOT NULL, -- When the event was received by the system
  value_long      NUMBER(20), -- Custom value, events can choose to store some event-specific value here. NOTE: 20 is probably waaaaaay to much.
  value_string    VARCHAR2(250), -- Custom value, events can choose to store some event-specific value here.
  value_float     FLOAT, -- Custom value, events can choose to store some event-specific value here.
  part_of         NUMBER(20), -- 1 to 1 with a top-level event
  PRIMARY KEY (event_id),
  FOREIGN KEY (event_type_id) REFERENCES MUSARK_STORAGE.EVENT_TYPE (event_type_id),
  FOREIGN KEY (part_of) REFERENCES MUSARK_STORAGE.EVENT (event_id)
);

CREATE TABLE MUSARK_STORAGE.LOCAL_OBJECT (
  object_id           NUMBER(20) NOT NULL,
  latest_move_id      NUMBER(20) NOT NULL,
  current_location_id NUMBER(20) NOT NULL,
  museum_id           INTEGER    NOT NULL,
  object_type         VARCHAR(50) DEFAULT 'collection', -- possible values can be 'collection', or 'sample'
  PRIMARY KEY (object_id),
  FOREIGN KEY (current_location_id) REFERENCES MUSARK_STORAGE.STORAGE_NODE (storage_node_id)
);

-- ???
CREATE TABLE MUSARK_STORAGE.EVENT_RELATION_EVENT (
  from_event_id NUMBER(20) NOT NULL,
  relation_id   INTEGER    NOT NULL,
  to_event_id   NUMBER(20) NOT NULL,
  FOREIGN KEY (from_event_id) REFERENCES MUSARK_STORAGE.EVENT (event_id),
  FOREIGN KEY (to_event_id) REFERENCES MUSARK_STORAGE.EVENT (event_id)
);

CREATE TABLE MUSARK_STORAGE.EVENT_ROLE_ACTOR (
  event_id   NUMBER(20)   NOT NULL,
  role_id    INTEGER      NOT NULL,
  actor_uuid VARCHAR2(36) NOT NULL, -- reference by Id to the ActorService
  PRIMARY KEY (event_id, role_id, actor_uuid),
  FOREIGN KEY (event_id) REFERENCES MUSARK_STORAGE.EVENT (event_id),
  FOREIGN KEY (role_id) REFERENCES MUSARK_STORAGE.ROLE (role_id)
);

CREATE TABLE MUSARK_STORAGE.EVENT_ROLE_OBJECT (
  event_id      NUMBER(20) NOT NULL,
  role_id       INTEGER    NOT NULL,
  object_id     NUMBER(20) NOT NULL,
  event_type_id NUMBER(20) NOT NULL,
  PRIMARY KEY (event_id, role_id, object_id),
  FOREIGN KEY (event_id) REFERENCES MUSARK_STORAGE.EVENT (event_id),
  FOREIGN KEY (role_id) REFERENCES MUSARK_STORAGE.ROLE (role_id),
  FOREIGN KEY (object_id) REFERENCES MUSARK_STORAGE.LOCAL_OBJECT (object_id)
);

-- This is the generic event-to-place relation, the place of where an event
-- happened, the place of where something was moved to etc.
CREATE TABLE MUSARK_STORAGE.EVENT_ROLE_PLACE (
  event_id      NUMBER(20) NOT NULL,
  role_id       INTEGER    NOT NULL,
  place_id      NUMBER(20) NOT NULL,
  event_type_id NUMBER(20) NOT NULL,
  PRIMARY KEY (event_id, role_id, place_id),
  FOREIGN KEY (event_id) REFERENCES MUSARK_STORAGE.EVENT (event_id),
  FOREIGN KEY (role_id) REFERENCES MUSARK_STORAGE.ROLE (role_id),
  FOREIGN KEY (place_id) REFERENCES MUSARK_STORAGE.STORAGE_NODE (storage_node_id)
);

-- For some event types, the "objects" really are places. Read it as
-- Event_Role_PlaceAsObject. This situation is stored in this table. We could
-- have used the EVENT_ROLE_OBJECT, but then we would loose foreign keys and
-- would have needed to tag which is which.
CREATE TABLE MUSARK_STORAGE.EVENT_ROLE_PLACE_AS_OBJECT (
  event_id      NUMBER(20) NOT NULL,
  role_id       INTEGER    NOT NULL,
  place_id      NUMBER(20) NOT NULL,
  event_type_id NUMBER(20) NOT NULL,
  PRIMARY KEY (event_id, role_id, place_id),
  FOREIGN KEY (event_id) REFERENCES MUSARK_STORAGE.EVENT (event_id),
  FOREIGN KEY (role_id) REFERENCES MUSARK_STORAGE.ROLE (role_id),
  FOREIGN KEY (place_id) REFERENCES MUSARK_STORAGE.STORAGE_NODE (storage_node_id)
);

-- ===========================================================================
-- Tables for Events with additional attributes. These do not fit into the
-- three columns set aside for the custom attributes in the EVENT table.
-- ===========================================================================

-- Contains data for Events that have a FROM -> TO structure.
CREATE TABLE MUSARK_STORAGE.OBSERVATION_FROM_TO (
  event_id   NUMBER(20) NOT NULL,
  value_from NUMBER,
  value_to   NUMBER,
  PRIMARY KEY (event_id),
  FOREIGN KEY (event_id) REFERENCES MUSARK_STORAGE.EVENT (event_id)
);

-- Contains extra data for storing environment requirement.
CREATE TABLE MUSARK_STORAGE.E_ENVIRONMENT_REQUIREMENT (
  event_id          NUMBER(20) NOT NULL,
  temperature       NUMBER,
  temp_tolerance    INTEGER,
  rel_humidity      NUMBER,
  rel_hum_tolerance INTEGER,
  hypoxic_air       NUMBER,
  hyp_air_tolerance INTEGER,
  cleaning          VARCHAR2(250),
  light             VARCHAR2(250),
  PRIMARY KEY (event_id),
  FOREIGN KEY (event_id) REFERENCES MUSARK_STORAGE.EVENT (event_id)
);

-- Contains extra data for storing info about a pest lifecycle. It is used by
-- the ObservationPest event which can have many of these.
CREATE TABLE MUSARK_STORAGE.OBSERVATION_PEST_LIFECYCLE (
  event_id NUMBER(20) NOT NULL,
  stage    VARCHAR2(250),
  quantity INTEGER,
  FOREIGN KEY (event_id) REFERENCES MUSARK_STORAGE.EVENT (event_id)
);

-- Required for testing purposes
CREATE SCHEMA IF NOT EXISTS MUSIT_MAPPING;

CREATE TABLE MUSIT_MAPPING.MUSITTHING (
  object_id         NUMBER(20) GENERATED BY DEFAULT AS IDENTITY,
  museumNo          VARCHAR(100) NOT NULL,
  subNo             VARCHAR(100),
  term              VARCHAR(256) NOT NULL,
  museumId          INTEGER      NOT NULL,
  museumNoAsNumber  INTEGER,
  subNoAsNumber     INTEGER,
  mainobject_id     NUMBER(20),
  is_deleted        INTEGER DEFAULT 0 NOT NULL,
  old_schemaname    VARCHAR(500),
  lokal_pk          NUMBER(20),
  old_barcode       NUMBER(20),
  new_collection_id INTEGER,
  musitthing_uuid   VARCHAR(36),
  PRIMARY KEY (object_id)
);

-- ===========================================================================
-- Pre-populating necessary data
-- ===========================================================================
-- TopLevel event types
INSERT INTO MUSARK_STORAGE.EVENT_TYPE (event_type_id, name) VALUES (1, 'MoveObject');
INSERT INTO MUSARK_STORAGE.EVENT_TYPE (event_type_id, name) VALUES (2, 'MovePlace');
INSERT INTO MUSARK_STORAGE.EVENT_TYPE (event_type_id, name) VALUES (3, 'EnvRequirement');
INSERT INTO MUSARK_STORAGE.EVENT_TYPE (event_type_id, name) VALUES (4, 'Control');
INSERT INTO MUSARK_STORAGE.EVENT_TYPE (event_type_id, name) VALUES (5, 'Observation');

-- Control sub-event types
INSERT INTO MUSARK_STORAGE.EVENT_TYPE (event_type_id, name) VALUES (6, 'ControlAlcohol');
INSERT INTO MUSARK_STORAGE.EVENT_TYPE (event_type_id, name) VALUES (7, 'ControlCleaning');
INSERT INTO MUSARK_STORAGE.EVENT_TYPE (event_type_id, name) VALUES (8, 'ControlGas');
INSERT INTO MUSARK_STORAGE.EVENT_TYPE (event_type_id, name) VALUES (9, 'ControlHypoxicAir');
INSERT INTO MUSARK_STORAGE.EVENT_TYPE (event_type_id, name) VALUES (10, 'ControlLightingCondition');
INSERT INTO MUSARK_STORAGE.EVENT_TYPE (event_type_id, name) VALUES (11, 'ControlMold');
INSERT INTO MUSARK_STORAGE.EVENT_TYPE (event_type_id, name) VALUES (12, 'ControlPest');
INSERT INTO MUSARK_STORAGE.EVENT_TYPE (event_type_id, name) VALUES (13, 'ControlRelativeHumidity');
INSERT INTO MUSARK_STORAGE.EVENT_TYPE (event_type_id, name) VALUES (14, 'ControlTemperature');

-- Observation sub-event types
INSERT INTO MUSARK_STORAGE.EVENT_TYPE (event_type_id, name) VALUES (15, 'ObservationAlcohol');
INSERT INTO MUSARK_STORAGE.EVENT_TYPE (event_type_id, name) VALUES (16, 'ObservationCleaning');
INSERT INTO MUSARK_STORAGE.EVENT_TYPE (event_type_id, name) VALUES (17, 'ObservationFireProtection');
INSERT INTO MUSARK_STORAGE.EVENT_TYPE (event_type_id, name) VALUES (18, 'ObservationGas');
INSERT INTO MUSARK_STORAGE.EVENT_TYPE (event_type_id, name) VALUES (19, 'ObservationHypoxicAir');
INSERT INTO MUSARK_STORAGE.EVENT_TYPE (event_type_id, name) VALUES (20, 'ObservationLightingCondition');
INSERT INTO MUSARK_STORAGE.EVENT_TYPE (event_type_id, name) VALUES (21, 'ObservationMold');
INSERT INTO MUSARK_STORAGE.EVENT_TYPE (event_type_id, name) VALUES (22, 'ObservationPerimeterSecurity');
INSERT INTO MUSARK_STORAGE.EVENT_TYPE (event_type_id, name) VALUES (23, 'ObservationRelativeHumidity');
INSERT INTO MUSARK_STORAGE.EVENT_TYPE (event_type_id, name) VALUES (24, 'ObservationPest');
INSERT INTO MUSARK_STORAGE.EVENT_TYPE (event_type_id, name) VALUES (25, 'ObservationTemperature');
INSERT INTO MUSARK_STORAGE.EVENT_TYPE (event_type_id, name) VALUES (26, 'ObservationTheftProtection');
INSERT INTO MUSARK_STORAGE.EVENT_TYPE (event_type_id, name) VALUES (27, 'ObservationWaterDamageAssessment');

-- Inserting roles
INSERT INTO MUSARK_STORAGE.ROLE (role_id, name, data_type) VALUES (1, 'DoneWith', 'object');
INSERT INTO MUSARK_STORAGE.ROLE (role_id, name, data_type) VALUES (2, 'DoneBy', 'actor');
INSERT INTO MUSARK_STORAGE.ROLE (role_id, name, data_type) VALUES (3, 'toPlace', 'storageNode');
INSERT INTO MUSARK_STORAGE.ROLE (role_id, name, data_type) VALUES (4, 'fromPlace', 'storageNode');

-- Inserting nodes
INSERT INTO MUSARK_STORAGE.STORAGE_NODE (STORAGE_NODE_UUID, STORAGE_NODE_NAME, IS_STORAGE_UNIT, IS_PART_OF, STORAGE_TYPE, NODE_PATH, MUSEUM_ID, UPDATED_BY, UPDATED_DATE)              VALUES ('dca44956-40d0-48dc-bd0d-921b825ad019', 'Utviklingsmuseet'    , '1', NULL, 'Root'        , ',1,'       , 99, '896125d3-0563-46b6-a7c5-51f3f899ff0a', TO_DATE('2016-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO MUSARK_STORAGE.STORAGE_NODE (STORAGE_NODE_UUID, STORAGE_NODE_NAME, IS_STORAGE_UNIT, IS_PART_OF, STORAGE_TYPE, NODE_PATH, MUSEUM_ID, UPDATED_BY, UPDATED_DATE)              VALUES ('b56b654a-6de3-442f-97af-ca6d806cc5a6', 'Utenfor museet'      , '1', NULL, 'RootLoan'    , ',2,'       , 99, '896125d3-0563-46b6-a7c5-51f3f899ff0a', TO_DATE('2016-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO MUSARK_STORAGE.STORAGE_NODE (STORAGE_NODE_UUID, STORAGE_NODE_NAME, IS_STORAGE_UNIT, IS_PART_OF, STORAGE_TYPE, NODE_PATH, MUSEUM_ID, UPDATED_BY, UPDATED_DATE)              VALUES ('d3982b48-56c7-4d27-bc81-6e38b59d57ed', 'Utviklingsmuseet Org', '1', 1   , 'Organisation', ',1,3,'     , 99, 'd63ab290-2fab-42d2-9b57-2475dfbd0b3c', TO_DATE('2016-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO MUSARK_STORAGE.STORAGE_NODE (STORAGE_NODE_UUID, STORAGE_NODE_NAME, IS_STORAGE_UNIT, IS_PART_OF, STORAGE_TYPE, NODE_PATH, MUSEUM_ID, UPDATED_BY, UPDATED_DATE)              VALUES ('3562e09e-6cf4-4b27-acad-e655e771c016', 'Forskningens hus'    , '1', 3   , 'Building'    , ',1,3,4,'   , 99, 'd63ab290-2fab-42d2-9b57-2475dfbd0b3c', TO_DATE('2016-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO MUSARK_STORAGE.STORAGE_NODE (STORAGE_NODE_UUID, STORAGE_NODE_NAME, IS_STORAGE_UNIT, IS_PART_OF, STORAGE_TYPE, NODE_PATH, MUSEUM_ID, UPDATED_BY, UPDATED_DATE)              VALUES ('01134afe-b262-434b-a71f-8f697bc75e56', 'Kulturværelset'      , '1', 4   , 'Room'        , ',1,3,4,5,' , 99, 'd63ab290-2fab-42d2-9b57-2475dfbd0b3c', TO_DATE('2016-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO MUSARK_STORAGE.STORAGE_NODE (STORAGE_NODE_UUID, STORAGE_NODE_NAME, IS_STORAGE_UNIT, IS_PART_OF, STORAGE_TYPE, NODE_PATH, MUSEUM_ID, UPDATED_BY, UPDATED_DATE)              VALUES ('244f09a3-eb1a-49e7-80ee-7a07baa016dd', 'Naturværelset'       , '1', 5   , 'Room'        , ',1,3,4,6,' , 99, 'd63ab290-2fab-42d2-9b57-2475dfbd0b3c', TO_DATE('2016-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO MUSARK_STORAGE.STORAGE_NODE (STORAGE_NODE_UUID, STORAGE_NODE_NAME, IS_STORAGE_UNIT, IS_PART_OF, STORAGE_TYPE, NODE_PATH, MUSEUM_ID, UPDATED_BY, UPDATED_DATE)              VALUES ('6e5b9810-9bbf-464a-a0b9-c27f6095ba0c', 'Forskningsværelset'  , '1', 6   , 'Room'        , ',1,3,4,7,' , 99, 'd63ab290-2fab-42d2-9b57-2475dfbd0b3c', TO_DATE('2016-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO MUSARK_STORAGE.STORAGE_NODE (STORAGE_NODE_UUID, STORAGE_NODE_NAME, IS_STORAGE_UNIT, IS_PART_OF, STORAGE_TYPE, NODE_PATH, MUSEUM_ID, UPDATED_BY, UPDATED_DATE, OLD_BARCODE) VALUES ('a02783b3-6ea6-41df-9085-8c8bba1b6d57', 'TestRoom 1'          , '1', 4   , 'Room'        , ',1,3,4,8,' , 99, 'd63ab290-2fab-42d2-9b57-2475dfbd0b3c', TO_DATE('2016-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 11111111);
INSERT INTO MUSARK_STORAGE.STORAGE_NODE (STORAGE_NODE_UUID, STORAGE_NODE_NAME, IS_STORAGE_UNIT, IS_PART_OF, STORAGE_TYPE, NODE_PATH, MUSEUM_ID, UPDATED_BY, UPDATED_DATE, OLD_BARCODE) VALUES ('1920ea73-aff2-46c9-b046-8d2087c8ac7e', 'TestRoom 2'          , '1', 4   , 'Room'        , ',1,3,4,9,' , 99, 'd63ab290-2fab-42d2-9b57-2475dfbd0b3c', TO_DATE('2016-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 11111112);
INSERT INTO MUSARK_STORAGE.STORAGE_NODE (STORAGE_NODE_UUID, STORAGE_NODE_NAME, IS_STORAGE_UNIT, IS_PART_OF, STORAGE_TYPE, NODE_PATH, MUSEUM_ID, UPDATED_BY, UPDATED_DATE, OLD_BARCODE) VALUES ('84ad2f9a-c43e-4b74-9531-0b9e5b074403', 'TestRoom 3'          , '1', 4   , 'Room'        , ',1,3,4,10,', 99, 'd63ab290-2fab-42d2-9b57-2475dfbd0b3c', TO_DATE('2016-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 11111113);
INSERT INTO MUSARK_STORAGE.STORAGE_NODE (STORAGE_NODE_UUID, STORAGE_NODE_NAME, IS_STORAGE_UNIT, IS_PART_OF, STORAGE_TYPE, NODE_PATH, MUSEUM_ID, UPDATED_BY, UPDATED_DATE, OLD_BARCODE) VALUES ('e45141cc-2f58-4bef-a576-9ad8f8b27448', 'TestRoom 4'          , '1', 4   , 'Room'        , ',1,3,4,11,', 99, 'd63ab290-2fab-42d2-9b57-2475dfbd0b3c', TO_DATE('2016-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 11111114);
INSERT INTO MUSARK_STORAGE.STORAGE_NODE (STORAGE_NODE_UUID, STORAGE_NODE_NAME, IS_STORAGE_UNIT, IS_PART_OF, STORAGE_TYPE, NODE_PATH, MUSEUM_ID, UPDATED_BY, UPDATED_DATE, OLD_BARCODE) VALUES ('28df80ab-6350-4290-95e6-470271eed849', 'TestRoom 5'          , '1', 4   , 'Room'        , ',1,3,4,12,', 99, 'd63ab290-2fab-42d2-9b57-2475dfbd0b3c', TO_DATE('2016-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 11111115);
INSERT INTO MUSARK_STORAGE.STORAGE_NODE (STORAGE_NODE_UUID, STORAGE_NODE_NAME, IS_STORAGE_UNIT, IS_PART_OF, STORAGE_TYPE, NODE_PATH, MUSEUM_ID, UPDATED_BY, UPDATED_DATE, OLD_BARCODE) VALUES ('16692a55-a01b-4f8f-b053-1772f150a8ec', 'TestRoom 6'          , '1', 4   , 'Room'        , ',1,3,4,13,', 99, 'd63ab290-2fab-42d2-9b57-2475dfbd0b3c', TO_DATE('2016-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 11111116);
INSERT INTO MUSARK_STORAGE.STORAGE_NODE (STORAGE_NODE_UUID, STORAGE_NODE_NAME, IS_STORAGE_UNIT, IS_PART_OF, STORAGE_TYPE, NODE_PATH, MUSEUM_ID, UPDATED_BY, UPDATED_DATE, OLD_BARCODE) VALUES ('770a45b8-33d8-47e9-9db2-631009279910', 'TestRoom 7'          , '1', 4   , 'Room'        , ',1,3,4,14,', 99, 'd63ab290-2fab-42d2-9b57-2475dfbd0b3c', TO_DATE('2016-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 11111117);
INSERT INTO MUSARK_STORAGE.STORAGE_NODE (STORAGE_NODE_UUID, STORAGE_NODE_NAME, IS_STORAGE_UNIT, IS_PART_OF, STORAGE_TYPE, NODE_PATH, MUSEUM_ID, UPDATED_BY, UPDATED_DATE, OLD_BARCODE) VALUES ('891969b3-2e64-4ed2-9737-b716eaa40198', 'TestRoom 8'          , '1', 4   , 'Room'        , ',1,3,4,15,', 99, 'd63ab290-2fab-42d2-9b57-2475dfbd0b3c', TO_DATE('2016-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 11111118);
INSERT INTO MUSARK_STORAGE.STORAGE_NODE (STORAGE_NODE_UUID, STORAGE_NODE_NAME, IS_STORAGE_UNIT, IS_PART_OF, STORAGE_TYPE, NODE_PATH, MUSEUM_ID, UPDATED_BY, UPDATED_DATE, OLD_BARCODE) VALUES ('b12bb4bf-778a-449a-bf89-647cca3c3dc3', 'TestRoom 9'          , '1', 4   , 'Room'        , ',1,3,4,16,', 99, 'd63ab290-2fab-42d2-9b57-2475dfbd0b3c', TO_DATE('2016-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 11111119);
INSERT INTO MUSARK_STORAGE.STORAGE_NODE (STORAGE_NODE_UUID, STORAGE_NODE_NAME, IS_STORAGE_UNIT, IS_PART_OF, STORAGE_TYPE, NODE_PATH, MUSEUM_ID, UPDATED_BY, UPDATED_DATE, OLD_BARCODE) VALUES ('af08788a-a85a-455f-b762-aa2c328ff90f', 'TestRoom 10'         , '1', 4   , 'Room'        , ',1,3,4,17,', 99, 'd63ab290-2fab-42d2-9b57-2475dfbd0b3c', TO_DATE('2016-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 11111110);

-- Specific node details
INSERT INTO MUSARK_STORAGE.ORGANISATION (STORAGE_NODE_ID, POSTAL_ADDRESS) VALUES (3, 'Foo Bar Street 1');
INSERT INTO MUSARK_STORAGE.BUILDING VALUES (4, NULL);
INSERT INTO MUSARK_STORAGE.ROOM VALUES (5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO MUSARK_STORAGE.ROOM VALUES (6, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO MUSARK_STORAGE.ROOM VALUES (7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO MUSARK_STORAGE.ROOM VALUES (8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO MUSARK_STORAGE.ROOM VALUES (9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO MUSARK_STORAGE.ROOM VALUES (10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO MUSARK_STORAGE.ROOM VALUES (11, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO MUSARK_STORAGE.ROOM VALUES (12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO MUSARK_STORAGE.ROOM VALUES (13, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO MUSARK_STORAGE.ROOM VALUES (14, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO MUSARK_STORAGE.ROOM VALUES (15, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO MUSARK_STORAGE.ROOM VALUES (16, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO MUSARK_STORAGE.ROOM VALUES (17, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

-- Inserting objects
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id, old_barcode) VALUES    ('37715843-36ab-4f1a-bcfb-dd68a05d0f2c', 'C666'  , '34' , 'Øks'        , 99, 666, 'USD_ARK_GJENSTAND_O', 100, 1, 1111111111);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id) VALUES                 ('8ae52969-63b8-42be-bfd0-d8ebef2169eb', 'C666'  , '31' , 'Sverd'      , 99, 666, 'USD_ARK_GJENSTAND_O', 101, 1);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id) VALUES                 ('d43e3c5a-8244-4497-bd15-29c844ff8745', 'C666'  , '38' , 'Sommerfugl' , 99, 666, 'USD_ARK_GJENSTAND_O', 102, 1);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id) VALUES                 ('a949277c-8233-4425-b3e8-8d6599e97531', 'C1'    , '1a' , 'Øks'        , 99, 1  , 'USD_ARK_GJENSTAND_O', 103, 1);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id) VALUES                 ('35522dc6-d246-4c7b-a23d-501bb34034f7', 'C1'    , '2a' , 'Skummel øks', 99, 1  , 'USD_ARK_GJENSTAND_O', 104, 1);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id) VALUES                 ('4d2e516d-db5f-478e-b409-eac7ff2486e8', 'C1'    , '3'  , 'Fin øks'    , 99, 1  , 'USD_ARK_GJENSTAND_O', 105, 1);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id) VALUES                 ('89f36f77-2c27-4d33-81b4-4d4f9688950d', 'C1'    , '4'  , 'Fin øks'    , 99, 1  , 'USD_ARK_GJENSTAND_O', 106, 1);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id) VALUES                 ('5a928d42-05a6-44db-adef-c6dfe588f016', 'C1'    , '5'  , 'Fin øks'    , 99, 1  , 'USD_ARK_GJENSTAND_O', 107, 1);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id) VALUES                 ('e11e89f5-b073-4874-9ced-c22152d5cb26', 'C1'    , '6'  , 'Fin øks'    , 99, 1  , 'USD_ARK_GJENSTAND_O', 108, 1);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id) VALUES                 ('7c951050-63a2-4afc-bab0-fa6d023f4dbd', 'C1'    , '7'  , 'Fin øks'    , 99, 1  , 'USD_ARK_GJENSTAND_O', 109, 1);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id) VALUES                 ('2e5037d5-4952-4571-9de2-709eb22b01f0', 'C1'    , '8'  , 'Fin øks'    , 99, 1  , 'USD_ARK_GJENSTAND_O', 110, 1);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id) VALUES                 ('aa309693-8d2e-41ae-a958-ada7dc4c914b', 'C1'    , '9'  , 'Fin øks'    , 99, 1  , 'USD_ARK_GJENSTAND_O', 111, 1);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id) VALUES                 ('08fd9b75-560e-4ad1-a62a-7eb945819c75', 'C1'    , '10a', 'Fin øks'    , 99, 1  , 'USD_ARK_GJENSTAND_O', 112, 1);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id) VALUES                 ('baec467b-2fd2-48d3-9fe1-6f0ea30a3497', 'C1'    , '11' , 'Fin øks'    , 99, 1  , 'USD_ARK_GJENSTAND_O', 113, 1);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id) VALUES                 ('86191223-2ff0-4776-b898-b79f1adb91af', 'C1'    , '12' , 'Fin øks'    , 99, 1  , 'USD_ARK_GJENSTAND_O', 114, 1);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id) VALUES                 ('7de44f6e-51f5-4c90-871b-cef8de0ce93d', 'C1'    , '13' , 'Fin øks'    , 99, 1  , 'USD_ARK_GJENSTAND_O', 115, 1);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id) VALUES                 ('9dfa0946-3b71-4382-888f-3f924ff48a77', 'C1'    , '14' , 'Fin øks'    , 99, 1  , 'USD_ARK_GJENSTAND_O', 116, 1);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id) VALUES                 ('2bd5eec5-c9ee-460c-ba54-ab23a4eea6fc', 'C1'    , '15' , 'Fin øks'    , 99, 1  , 'USD_ARK_GJENSTAND_O', 117, 1);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id) VALUES                 ('ac03f45e-57cf-484a-8947-af87dae8b1ae', 'C1'    , '16' , 'Fin øks'    , 99, 1  , 'USD_ARK_GJENSTAND_O', 118, 1);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id) VALUES                 ('3a71f423-52b2-4437-a62b-6e37ad406bcd', 'C1'    , '17' , 'Fin øks'    , 99, 1  , 'USD_ARK_GJENSTAND_O', 119, 1);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id, is_deleted) VALUES     ('317b1ce9-82c7-4412-ae99-df7fda342077', 'C1'    , '18' , 'Fin øks'    , 99, 1  , 'USD_ARK_GJENSTAND_O', 120, 1, 1);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id, is_deleted) VALUES     ('800c5235-3ad0-4245-8450-c3216c661bb1', 'C1'    , '19' , 'Fin øks'    , 99, 1  , 'USD_ARK_GJENSTAND_O', 121, 1, 1);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id) VALUES                 ('baab2f60-4f49-40fe-99c8-174b13b12d46', 'C1'    , '20b', 'Fin øks'    , 99, 1  , 'USD_ARK_GJENSTAND_O', 122, 1);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id) VALUES                 ('376d41e7-c463-45e8-9bde-7a2c9844637e', 'C1'    , '22' , 'Fin øks'    , 99, 1  , 'USD_ARK_GJENSTAND_O', 123, 1);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id) VALUES                 ('2350578d-0bb0-4601-92d4-817478ad0952', 'C1'    , '21' , 'Fin øks'    , 99, 1  , 'USD_ARK_GJENSTAND_O', 124, 1);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id) VALUES                 ('c182206b-530c-4a40-b9aa-fba044ecb953', 'C2'    , ''   , 'Sverd'      , 99, 1  , 'USD_ARK_GJENSTAND_O', 125, 1);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id) VALUES                 ('bf53f481-1db3-4474-98ee-c94df31ec251', 'C777'  , '35' , 'Øks'        , 99, 777, 'USD_ARK_GJENSTAND_O', 126, 1);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id) VALUES                 ('373bb138-ed93-472b-ad57-ccb77ab8c151', 'C.777' , '34B', 'Øks'        , 99, 777, 'USD_ARK_GJENSTAND_O', 127, 1);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id) VALUES                 ('62272640-e29e-4af4-a537-3c49b5f1cf42', 'C.777' , '34' , 'Øks'        , 99, 777, 'USD_ARK_GJENSTAND_O', 128, 1);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id) VALUES                 ('f4a189c3-4d8f-4258-9000-b23282814278', 'C.777' , '34A', 'Øks'        , 99, 777, 'USD_ARK_GJENSTAND_O', 129, 1);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id) VALUES                 ('67965e71-27ee-4ef0-ad66-e7e321882f33', 'C555'  , '34B', 'Øks'        , 99, 555, 'USD_ARK_GJENSTAND_O', 130, 1);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id) VALUES                 ('6f9db6a5-f994-4498-8ebc-c9ba75c51ce8', 'C555'  , '34A', 'Øks'        , 99, 555, 'USD_ARK_GJENSTAND_O', 131, 1);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id) VALUES                 ('b17b8735-2350-4de9-b812-93753b1eeb8d', 'C555'  , '34C', 'Øks'        , 99, 555, 'USD_ARK_GJENSTAND_O', 132, 1);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id) VALUES                 ('215542d3-48c9-44af-a6ea-4c494da54fe0', 'C555A' , 'B'  , 'Øks'        , 99, 555, 'USD_ARK_GJENSTAND_O', 133, 1);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id) VALUES                 ('065b9812-0f22-4ba4-bac2-7d7cbc850dcc', 'C555B' , 'A'  , 'Øks'        , 99, 555, 'USD_ARK_GJENSTAND_O', 134, 1);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id) VALUES                 ('6ca2bf73-fa17-4d41-a8da-ab9f46a7494b', 'C555C' , 'C'  , 'Øks'        , 99, 555, 'USD_ARK_GJENSTAND_O', 135, 1);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id) VALUES                 ('21dadc0d-50ca-41ea-9b48-90fdec515148', 'C888_B', 'B'  , 'Øks'        , 99, 888, 'USD_ARK_GJENSTAND_O', 136, 1);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id) VALUES                 ('7b2e3bd6-b699-4671-bd50-1d964342f531', 'C888_A', 'A'  , 'Øks'        , 99, 888, 'USD_ARK_GJENSTAND_O', 137, 1);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id) VALUES                 ('40898454-069e-41c9-9551-946a1e693f59', 'C888xC', 'C'  , 'Øks'        , 99, 888, 'USD_ARK_GJENSTAND_O', 138, 1);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id) VALUES                 ('f56bd93f-49b6-4111-b6c8-bd84a14ea98e', 'C81%A' , 'A'  , 'Bøtte'      , 99, 81 , 'USD_ARK_GJENSTAND_O', 139, 1);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id) VALUES                 ('b71d3bd7-28e3-4790-b4f6-98664e2385ba', 'C81%XA', 'B'  , 'Bøtte'      , 99, 81 , 'USD_ARK_GJENSTAND_O', 140, 1);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id) VALUES                 ('6ee89241-a404-4086-b373-c42dd0a2e56a', 'C81-A' , 'A'  , 'Bøtte'      , 99, 81 , 'USD_ARK_GJENSTAND_O', 141, 1);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id) VALUES                 ('5f7f0b2b-f2eb-480d-816e-00b140705f2b', 'C81-XA', 'B'  , 'Bøtte'      , 99, 81 , 'USD_ARK_GJENSTAND_O', 142, 1);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id) VALUES                 ('bbf9a3de-9203-4e90-9b04-4475e4f7f749', 'C81¤A' , 'A'  , 'Bøtte'      , 99, 81 , 'USD_ARK_GJENSTAND_O', 143, 1);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id) VALUES                 ('29339044-8696-4c76-9b3e-f153ae63d262', 'C81¤XA', 'B'  , 'Bøtte'      , 99, 81 , 'USD_ARK_GJENSTAND_O', 144, 1);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id) VALUES                 ('7ae2521e-904c-432b-998c-bb09810310a9', 'F555'  , '55A', 'Gammel mynt', 99, 555, 'USD_NUMISMATIKK'    , 145, 3);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id) VALUES                 ('42b6a92e-de59-4fde-9c46-5c8794be0b34', 'L234'  , ''   , 'Reinlav'    , 99, 234, 'MUSIT_BOTANIKK_LAV' , 146, 4);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id, mainobject_id) VALUES  ('331d8174-dfdb-47ae-8dc0-5aa7be59fe09', 'K123'  , ''   , 'Drakt'      , 99, 123, 'USD_ARK_GJENSTAND_O', 147, 1, 12);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id, mainobject_id) VALUES  ('6e7b9387-5f89-4388-8bbb-7eb727e58f09', 'K123'  , ''   , 'Skjorte'    , 99, 123, 'USD_ARK_GJENSTAND_O', 148, 1, 12);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id, mainobject_id) VALUES  ('2ce90a19-e190-4738-a344-42741f471cdc', 'K123'  , ''   , 'Kjole'      , 99, 123, 'USD_ARK_GJENSTAND_O', 149, 1, 12);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id) VALUES                 ('dcd37cb7-34ae-484e-a2c0-a1b1925e9b68', 'L234'  , ''   , 'Kartlav'    , 99, 234, 'MUSIT_BOTANIKK_LAV'  , 150, 4);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id) VALUES                 ('3fd8d3f9-ebb1-4447-8959-8e91ca2693fb', 'L234'  , ''   , 'Fokklav'    , 99, 234, 'MUSIT_BOTANIKK_LAV'  , 151, 4);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id) VALUES                 ('564fade0-4a41-47cc-8c26-3b8f048aa191', 'L234'  , ''   , 'Grønnever'  , 99, 234, 'MUSIT_BOTANIKK_LAV'  , 152, 4);
INSERT INTO MUSIT_MAPPING.MUSITTHING (musitthing_uuid, museumNo, subNo, term, museumId, museumNoAsNumber, old_schemaname, lokal_pk, new_collection_id) VALUES                 ('a738e36d-8683-44ac-9dda-67ff5a5851d5', 'L234'  , ''   , 'Islandslav' , 99, 234, 'MUSIT_BOTANIKK_LAV'  , 153, 4);

-- INSERT INTO MUSARK_STORAGE.LOCAL_OBJECT (OBJECT_ID, LATEST_MOVE_ID, CURRENT_LOCATION_ID, MUSEUM_ID) VALUES (1, 1, 5, 99);
INSERT INTO MUSARK_STORAGE.LOCAL_OBJECT (OBJECT_ID, LATEST_MOVE_ID, CURRENT_LOCATION_ID, MUSEUM_ID) VALUES (1, 9999, 5, 99);
INSERT INTO MUSARK_STORAGE.LOCAL_OBJECT (OBJECT_ID, LATEST_MOVE_ID, CURRENT_LOCATION_ID, MUSEUM_ID) VALUES (2, 9999, 5, 99);
INSERT INTO MUSARK_STORAGE.LOCAL_OBJECT (OBJECT_ID, LATEST_MOVE_ID, CURRENT_LOCATION_ID, MUSEUM_ID) VALUES (3, 9999, 5, 99);
INSERT INTO MUSARK_STORAGE.LOCAL_OBJECT (OBJECT_ID, LATEST_MOVE_ID, CURRENT_LOCATION_ID, MUSEUM_ID) VALUES (4, 9999, 5, 99);
INSERT INTO MUSARK_STORAGE.LOCAL_OBJECT (OBJECT_ID, LATEST_MOVE_ID, CURRENT_LOCATION_ID, MUSEUM_ID) VALUES (5, 9999, 6, 99);
INSERT INTO MUSARK_STORAGE.LOCAL_OBJECT (OBJECT_ID, LATEST_MOVE_ID, CURRENT_LOCATION_ID, MUSEUM_ID) VALUES (6, 9999, 6, 99);
INSERT INTO MUSARK_STORAGE.LOCAL_OBJECT (OBJECT_ID, LATEST_MOVE_ID, CURRENT_LOCATION_ID, MUSEUM_ID) VALUES (7, 9999, 6, 99);
INSERT INTO MUSARK_STORAGE.LOCAL_OBJECT (OBJECT_ID, LATEST_MOVE_ID, CURRENT_LOCATION_ID, MUSEUM_ID) VALUES (8, 9999, 6, 99);
INSERT INTO MUSARK_STORAGE.LOCAL_OBJECT (OBJECT_ID, LATEST_MOVE_ID, CURRENT_LOCATION_ID, MUSEUM_ID) VALUES (9, 9999, 6, 99);
INSERT INTO MUSARK_STORAGE.LOCAL_OBJECT (OBJECT_ID, LATEST_MOVE_ID, CURRENT_LOCATION_ID, MUSEUM_ID) VALUES (10, 9999, 7, 99);
INSERT INTO MUSARK_STORAGE.LOCAL_OBJECT (OBJECT_ID, LATEST_MOVE_ID, CURRENT_LOCATION_ID, MUSEUM_ID) VALUES (11, 9999, 7, 99);
INSERT INTO MUSARK_STORAGE.LOCAL_OBJECT (OBJECT_ID, LATEST_MOVE_ID, CURRENT_LOCATION_ID, MUSEUM_ID) VALUES (12, 9999, 7, 99);
INSERT INTO MUSARK_STORAGE.LOCAL_OBJECT (OBJECT_ID, LATEST_MOVE_ID, CURRENT_LOCATION_ID, MUSEUM_ID) VALUES (13, 9999, 7, 99);
INSERT INTO MUSARK_STORAGE.LOCAL_OBJECT (OBJECT_ID, LATEST_MOVE_ID, CURRENT_LOCATION_ID, MUSEUM_ID, OBJECT_TYPE) VALUES (20, 9999, 8, 99, 'collection');
INSERT INTO MUSARK_STORAGE.LOCAL_OBJECT (OBJECT_ID, LATEST_MOVE_ID, CURRENT_LOCATION_ID, MUSEUM_ID, OBJECT_TYPE) VALUES (21, 9999, 9, 99, 'sample');

INSERT INTO MUSARK_STORAGE.NEW_LOCAL_OBJECT (OBJECT_UUID, LATEST_MOVE_ID, CURRENT_LOCATION_ID, MUSEUM_ID)              VALUES ('37715843-36ab-4f1a-bcfb-dd68a05d0f2c', 9999, '01134afe-b262-434b-a71f-8f697bc75e56', 99);
INSERT INTO MUSARK_STORAGE.NEW_LOCAL_OBJECT (OBJECT_UUID, LATEST_MOVE_ID, CURRENT_LOCATION_ID, MUSEUM_ID)              VALUES ('8ae52969-63b8-42be-bfd0-d8ebef2169eb', 9999, '01134afe-b262-434b-a71f-8f697bc75e56', 99);
INSERT INTO MUSARK_STORAGE.NEW_LOCAL_OBJECT (OBJECT_UUID, LATEST_MOVE_ID, CURRENT_LOCATION_ID, MUSEUM_ID)              VALUES ('d43e3c5a-8244-4497-bd15-29c844ff8745', 9999, '01134afe-b262-434b-a71f-8f697bc75e56', 99);
INSERT INTO MUSARK_STORAGE.NEW_LOCAL_OBJECT (OBJECT_UUID, LATEST_MOVE_ID, CURRENT_LOCATION_ID, MUSEUM_ID)              VALUES ('a949277c-8233-4425-b3e8-8d6599e97531', 9999, '01134afe-b262-434b-a71f-8f697bc75e56', 99);
INSERT INTO MUSARK_STORAGE.NEW_LOCAL_OBJECT (OBJECT_UUID, LATEST_MOVE_ID, CURRENT_LOCATION_ID, MUSEUM_ID)              VALUES ('35522dc6-d246-4c7b-a23d-501bb34034f7', 9999, '244f09a3-eb1a-49e7-80ee-7a07baa016dd', 99);
INSERT INTO MUSARK_STORAGE.NEW_LOCAL_OBJECT (OBJECT_UUID, LATEST_MOVE_ID, CURRENT_LOCATION_ID, MUSEUM_ID)              VALUES ('4d2e516d-db5f-478e-b409-eac7ff2486e8', 9999, '244f09a3-eb1a-49e7-80ee-7a07baa016dd', 99);
INSERT INTO MUSARK_STORAGE.NEW_LOCAL_OBJECT (OBJECT_UUID, LATEST_MOVE_ID, CURRENT_LOCATION_ID, MUSEUM_ID)              VALUES ('89f36f77-2c27-4d33-81b4-4d4f9688950d', 9999, '244f09a3-eb1a-49e7-80ee-7a07baa016dd', 99);
INSERT INTO MUSARK_STORAGE.NEW_LOCAL_OBJECT (OBJECT_UUID, LATEST_MOVE_ID, CURRENT_LOCATION_ID, MUSEUM_ID)              VALUES ('5a928d42-05a6-44db-adef-c6dfe588f016', 9999, '244f09a3-eb1a-49e7-80ee-7a07baa016dd', 99);
INSERT INTO MUSARK_STORAGE.NEW_LOCAL_OBJECT (OBJECT_UUID, LATEST_MOVE_ID, CURRENT_LOCATION_ID, MUSEUM_ID)              VALUES ('e11e89f5-b073-4874-9ced-c22152d5cb26', 9999, '244f09a3-eb1a-49e7-80ee-7a07baa016dd', 99);
INSERT INTO MUSARK_STORAGE.NEW_LOCAL_OBJECT (OBJECT_UUID, LATEST_MOVE_ID, CURRENT_LOCATION_ID, MUSEUM_ID)              VALUES ('7c951050-63a2-4afc-bab0-fa6d023f4dbd', 9999, '6e5b9810-9bbf-464a-a0b9-c27f6095ba0c', 99);
INSERT INTO MUSARK_STORAGE.NEW_LOCAL_OBJECT (OBJECT_UUID, LATEST_MOVE_ID, CURRENT_LOCATION_ID, MUSEUM_ID)              VALUES ('2e5037d5-4952-4571-9de2-709eb22b01f0', 9999, '6e5b9810-9bbf-464a-a0b9-c27f6095ba0c', 99);
INSERT INTO MUSARK_STORAGE.NEW_LOCAL_OBJECT (OBJECT_UUID, LATEST_MOVE_ID, CURRENT_LOCATION_ID, MUSEUM_ID)              VALUES ('aa309693-8d2e-41ae-a958-ada7dc4c914b', 9999, '6e5b9810-9bbf-464a-a0b9-c27f6095ba0c', 99);
INSERT INTO MUSARK_STORAGE.NEW_LOCAL_OBJECT (OBJECT_UUID, LATEST_MOVE_ID, CURRENT_LOCATION_ID, MUSEUM_ID)              VALUES ('08fd9b75-560e-4ad1-a62a-7eb945819c75', 9999, '6e5b9810-9bbf-464a-a0b9-c27f6095ba0c', 99);
INSERT INTO MUSARK_STORAGE.NEW_LOCAL_OBJECT (OBJECT_UUID, LATEST_MOVE_ID, CURRENT_LOCATION_ID, MUSEUM_ID, OBJECT_TYPE) VALUES ('3a71f423-52b2-4437-a62b-6e37ad406bcd', 9999, 'a02783b3-6ea6-41df-9085-8c8bba1b6d57', 99, 'collection');
INSERT INTO MUSARK_STORAGE.NEW_LOCAL_OBJECT (OBJECT_UUID, LATEST_MOVE_ID, CURRENT_LOCATION_ID, MUSEUM_ID, OBJECT_TYPE) VALUES ('baab2f60-4f49-40fe-99c8-174b13b12d46', 9999, '1920ea73-aff2-46c9-b046-8d2087c8ac7e', 99, 'sample');

INSERT INTO MUSARK_STORAGE.NEW_LOCAL_OBJECT (OBJECT_UUID, LATEST_MOVE_ID, CURRENT_LOCATION_ID, MUSEUM_ID) VALUES ('2b39c741-5e32-49b5-90cd-fe90630b3f89', 9999, '01134afe-b262-434b-a71f-8f697bc75e56', 99);
INSERT INTO MUSARK_STORAGE.NEW_LOCAL_OBJECT (OBJECT_UUID, LATEST_MOVE_ID, CURRENT_LOCATION_ID, MUSEUM_ID) VALUES ('e2cdc938-70d0-44f8-89b5-ae9387e1cc61', 9999, '01134afe-b262-434b-a71f-8f697bc75e56', 99);
INSERT INTO MUSARK_STORAGE.NEW_LOCAL_OBJECT (OBJECT_UUID, LATEST_MOVE_ID, CURRENT_LOCATION_ID, MUSEUM_ID) VALUES ('7d95a780-9a34-4fc9-9176-f09cd5c75aa2', 9999, '01134afe-b262-434b-a71f-8f697bc75e56', 99);
INSERT INTO MUSARK_STORAGE.NEW_LOCAL_OBJECT (OBJECT_UUID, LATEST_MOVE_ID, CURRENT_LOCATION_ID, MUSEUM_ID) VALUES ('2f17d88e-34ca-474b-98ed-9fe80852fb42', 9999, '01134afe-b262-434b-a71f-8f697bc75e56', 99);
INSERT INTO MUSARK_STORAGE.NEW_LOCAL_OBJECT (OBJECT_UUID, LATEST_MOVE_ID, CURRENT_LOCATION_ID, MUSEUM_ID) VALUES ('7f116e44-61e4-4f4c-9735-e25e9ccf12bf', 9999, '244f09a3-eb1a-49e7-80ee-7a07baa016dd', 99);
INSERT INTO MUSARK_STORAGE.NEW_LOCAL_OBJECT (OBJECT_UUID, LATEST_MOVE_ID, CURRENT_LOCATION_ID, MUSEUM_ID) VALUES ('0ff38a94-5c9d-4139-bab1-84760e56780f', 9999, '244f09a3-eb1a-49e7-80ee-7a07baa016dd', 99);
INSERT INTO MUSARK_STORAGE.NEW_LOCAL_OBJECT (OBJECT_UUID, LATEST_MOVE_ID, CURRENT_LOCATION_ID, MUSEUM_ID) VALUES ('f9c15233-81fe-43f6-9cfc-e6831b534342', 9999, '244f09a3-eb1a-49e7-80ee-7a07baa016dd', 99);
INSERT INTO MUSARK_STORAGE.NEW_LOCAL_OBJECT (OBJECT_UUID, LATEST_MOVE_ID, CURRENT_LOCATION_ID, MUSEUM_ID) VALUES ('0b02b0d0-91a9-4318-86f6-773e7a7ffa29', 9999, '244f09a3-eb1a-49e7-80ee-7a07baa016dd', 99);
INSERT INTO MUSARK_STORAGE.NEW_LOCAL_OBJECT (OBJECT_UUID, LATEST_MOVE_ID, CURRENT_LOCATION_ID, MUSEUM_ID) VALUES ('8ecb72cc-1993-41a4-8461-9b0d49e17813', 9999, '244f09a3-eb1a-49e7-80ee-7a07baa016dd', 99);
INSERT INTO MUSARK_STORAGE.NEW_LOCAL_OBJECT (OBJECT_UUID, LATEST_MOVE_ID, CURRENT_LOCATION_ID, MUSEUM_ID) VALUES ('ccf0d821-5292-4f84-bab5-410e029f6b21', 9999, '6e5b9810-9bbf-464a-a0b9-c27f6095ba0c', 99);
INSERT INTO MUSARK_STORAGE.NEW_LOCAL_OBJECT (OBJECT_UUID, LATEST_MOVE_ID, CURRENT_LOCATION_ID, MUSEUM_ID) VALUES ('45968c80-a6aa-4fd6-9175-dfeff17df711', 9999, '6e5b9810-9bbf-464a-a0b9-c27f6095ba0c', 99);
INSERT INTO MUSARK_STORAGE.NEW_LOCAL_OBJECT (OBJECT_UUID, LATEST_MOVE_ID, CURRENT_LOCATION_ID, MUSEUM_ID) VALUES ('b5812db3-1c72-4f34-b0a3-f5be3d7a093b', 9999, '6e5b9810-9bbf-464a-a0b9-c27f6095ba0c', 99);
INSERT INTO MUSARK_STORAGE.NEW_LOCAL_OBJECT (OBJECT_UUID, LATEST_MOVE_ID, CURRENT_LOCATION_ID, MUSEUM_ID) VALUES ('b1b919ed-4280-4c0e-943d-7e45b3a56058', 9999, '6e5b9810-9bbf-464a-a0b9-c27f6095ba0c', 99);


-- INSERT INTO MUSARK_STORAGE.EVENT VALUES (1, 1, NULL, TO_DATE('2016-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '6a32a1d9-ffea-4979-880c-37ea620d4e2c', TO_DATE('2016-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, NULL, NULL);
-- INSERT INTO MUSARK_STORAGE.EVENT_ROLE_PLACE VALUES (1, 3, 5, 1);
-- INSERT INTO MUSARK_STORAGE.EVENT_ROLE_PLACE VALUES (1, 4, 10, 1);
-- INSERT INTO MUSARK_STORAGE.EVENT_ROLE_ACTOR VALUES (1, 2, '51b2ff65-18fd-4b98-9079-b1e49c69f563');
-- INSERT INTO MUSARK_STORAGE.EVENT_ROLE_OBJECT VALUES (1, 1, 1, 1);

# --- !Downs
