# --- !Ups

CREATE SCHEMA IF NOT EXISTS MUSIT_MAPPING;

CREATE TABLE MUSIT_MAPPING.VIEW_MUSITTHING (
 id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
 displayId VARCHAR NOT NULL,
 displayName VARCHAR
);

CREATE SCHEMA IF NOT EXISTS MUSARK_STORAGE;

CREATE TABLE MUSARK_STORAGE.LOCAL_OBJECT (
 object_id BIGINT(20) NOT NULL,
 latest_move_id BIGINT(20),
 current_location_id INTEGER,
 museum_id INTEGER NOT NULL,
 FOREIGN KEY(object_id) REFERENCES MUSIT_MAPPING.VIEW_MUSITTHING(id)
);

CREATE TABLE MUSARK_STORAGE.STORAGE_NODE (
 storage_node_id BIGINT NOT NULL AUTO_INCREMENT,
 museum_id INTEGER NOT NULL,
 PRIMARY KEY (storage_node_id)
);

CREATE TABLE MUSIT_MAPPING.MUSITTHING (
 id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
 museumNo VARCHAR NOT NULL,
 subNo VARCHAR,
 term VARCHAR NOT NULL,
 museumId INTEGER NOT NULL,
 museumNoAsNumber BIGINT,
 subNoAsNumber BIGINT
);