package models

import models.SampleStatuses.SampleStatus
import no.uio.musit.models.{ActorId, MuseumId, ObjectUUID}
import org.joda.time.DateTime
import play.api.libs.json.{Format, Json}

case class SampleObject(
  objectId: Option[ObjectUUID],
  parentObjectId: Option[ObjectUUID],
  isCollectionObject: Boolean,
  museumId: MuseumId,
  status: SampleStatus,
  responsible: ActorId,
  createdDate: DateTime,
  // TODO: Add autogenerated sample ID
  sampleId: Option[String],
  externalId: Option[String],
  note: Option[String],
  registeredBy: Option[ActorId],
  registeredDate: Option[DateTime],
  updatedBy: Option[ActorId],
  updatedDate: Option[DateTime]
)

object SampleObject {

  implicit val format: Format[SampleObject] = Json.format[SampleObject]

}
