# --- !Ups

CREATE SCHEMA IF NOT EXISTS MUSARK_ANALYSIS;

CREATE TABLE MUSARK_ANALYSIS.ANALYSIS_EVENT (
  event_id        NUMBER(20) GENERATED BY DEFAULT AS IDENTITY,
  event_type      INTEGER      NOT NULL,
  event_date      TIMESTAMP    NOT NULL,
  registered_by   VARCHAR2(36) NOT NULL,
  registered_date TIMESTAMP    NOT NULL, -- When the event was received by the system
  event_json      CLOB,
  PRIMARY KEY (event_id),
  CONSTRAINT ensure_json CHECK (event_json IS JSON)
);


