version: "2"
services:
    nginx:
        build:
            context: "./nginx"
        ports:
            - "80:80"
        links:
            - backing
            - webpack

    webpack:
        build:
            context: "../../frontend"
        environment:
          - REACT_APP_USE_DATAPORTEN

    backing:
        build:
          context: "../../backing"
        environment:
          - CLIENT_ID
          - CLIENT_SECRET
          - CALLBACK_URL
          - JWT_SECRET
        ports:
          - "3030:3030"

    db:
        image: postgres:9.5
        environment:
          - POSTGRES_USER
          - POSTGRES_PASSWORD
          - POSTGRES_DB
        volumes:
          - ../../../postgres-storage:/var/lib/postgresql/data/

    thingaggregate:
        image: musit_service_thing_aggregate:0.1-SNAPSHOT
        environment:
          - MUSIT_SECURITY_MODULE
          - DATAPORTEN_CLIENT_ID
          - DATAPORTEN_CLIENT_SECRET
          - APPLICATION_SECRET
          - EVOLUTION_ENABLED
          - SLICK_DRIVER
          - SLICK_DB_DRIVER
          - SLICK_DB_URL
          - SLICK_DB_USER
          - SLICK_DB_PASSWORD
        links:
          - db

    actor:
        image: musit_service_actor:0.1-SNAPSHOT
        environment:
          - MUSIT_SECURITY_MODULE
          - DATAPORTEN_CLIENT_ID
          - DATAPORTEN_CLIENT_SECRET
          - APPLICATION_SECRET
          - EVOLUTION_ENABLED
          - SLICK_DRIVER
          - SLICK_DB_DRIVER
          - SLICK_DB_URL
          - SLICK_DB_USER
          - SLICK_DB_PASSWORD
        links:
          - db

    geolocation:
        image: musit_service_geo_location:0.1-SNAPSHOT
        environment:
          - MUSIT_SECURITY_MODULE
          - DATAPORTEN_CLIENT_ID
          - DATAPORTEN_CLIENT_SECRET
          - APPLICATION_SECRET

    auth:
        image: musit_service_auth:0.1-SNAPSHOT
        ports:
          - "7074:7070"
        environment:
          - MUSIT_SECURITY_MODULE
          - DATAPORTEN_CLIENT_ID
          - DATAPORTEN_CLIENT_SECRET
          - APPLICATION_SECRET
          - EVOLUTION_ENABLED
          - SLICK_DRIVER
          - SLICK_DB_DRIVER
          - SLICK_DB_URL
          - SLICK_DB_USER
          - SLICK_DB_PASSWORD
        links:
          - db
          - actor

    storagefacility:
        image: musit_service_storagefacility:0.1-SNAPSHOT
        environment:
          - MUSIT_SECURITY_MODULE
          - DATAPORTEN_CLIENT_ID
          - DATAPORTEN_CLIENT_SECRET
          - APPLICATION_SECRET
          - EVOLUTION_ENABLED
          - SLICK_DRIVER
          - SLICK_DB_DRIVER
          - SLICK_DB_URL
          - SLICK_DB_USER
          - SLICK_DB_PASSWORD
        links:
          - db
