version: "2"
services:
  nginx:
    build:
      context: "./nginx"
    ports:
      - "80:80"
    links:
      - webpack
      - backend
      - auth
      - barcode

  webpack:
    build:
      context: "../../frontend"
    environment:
      - REACT_APP_USE_DATAPORTEN

  backend:
    image: service_backend:0.1-SNAPSHOT
    environment:
      - MUSIT_ENV
      - MUSIT_BASE_URL
      - DOCKER_HOSTNAME
      - MUSIT_SECURITY_MODULE
      - DATAPORTEN_CLIENT_ID
      - DATAPORTEN_CLIENT_SECRET
      - DATAPORTEN_SESSION_TIMEOUT
      - APPLICATION_SECRET
      - EVOLUTION_ENABLED
      - SLICK_DB_URL
      - SLICK_DB_USER
      - SLICK_DB_PASSWORD
      - ELASTICSEARCH_HOST

  auth:
    image: service_auth:0.1-SNAPSHOT
    environment:
      - MUSIT_ENV
      - MUSIT_BASE_URL
      - DOCKER_HOSTNAME
      - MUSIT_SECURITY_MODULE
      - CALLBACK_URL
      - DATAPORTEN_CLIENT_ID
      - DATAPORTEN_CLIENT_SECRET
      - DATAPORTEN_SESSION_TIMEOUT
      - APPLICATION_SECRET
      - EVOLUTION_ENABLED
      - SLICK_DB_URL
      - SLICK_DB_USER
      - SLICK_DB_PASSWORD

  barcode:
    image: service_barcode:0.1-SNAPSHOT
    environment:
      - MUSIT_ENV
      - MUSIT_BASE_URL
      - DOCKER_HOSTNAME
      - MUSIT_SECURITY_MODULE
      - DATAPORTEN_CLIENT_ID
      - DATAPORTEN_CLIENT_SECRET
      - DATAPORTEN_SESSION_TIMEOUT
      - APPLICATION_SECRET
      - EVOLUTION_ENABLED
      - SLICK_DB_URL
      - SLICK_DB_USER
      - SLICK_DB_PASSWORD

  document:
    image: service_document:0.1-SNAPSHOT
    environment:
      - MUSIT_ENV
      - MUSIT_BASE_URL
      - DOCKER_HOSTNAME
      - MUSIT_SECURITY_MODULE
      - DATAPORTEN_CLIENT_ID
      - DATAPORTEN_CLIENT_SECRET
      - DATAPORTEN_SESSION_TIMEOUT
      - APPLICATION_SECRET
      - EVOLUTION_ENABLED
      - SLICK_DB_URL
      - SLICK_DB_USER
      - SLICK_DB_PASSWORD
      # Props for the document management library to connect to postgres
      - SYMBIOTIC_POSTGRES_HOST
      - SYMBIOTIC_POSTGRES_PORT
      - SYMBIOTIC_POSTGRES_USE_SSL
      - SYMBIOTIC_DB_USER
      - SYMBIOTIC_DB_PASSWORD
      - SYMBIOTIC_DB_NAME
      - SYMBIOTIC_FS_ROOT_DIR
