CREATE SCHEMA IF NOT EXISTS "MUSARK_STORAGE";

CREATE TABLE "MUSARK_STORAGE"."STORAGE_NODE" (
  "STORAGE_NODE_ID" BIGSERIAL,
  "STORAGE_NODE_NAME" VARCHAR(512),
  "AREA" DOUBLE PRECISION,
  "AREA_TO" DOUBLE PRECISION,
  "IS_STORAGE_UNIT" VARCHAR(1) DEFAULT '1',
  "IS_PART_OF" BIGINT,
  "HEIGHT" DOUBLE PRECISION,
  "HEIGHT_TO" DOUBLE PRECISION,
  "IS_DELETED" BOOLEAN NOT NULL,
  "STORAGE_TYPE" VARCHAR(100) DEFAULT 'StorageUnit',
  "GROUP_READ" VARCHAR(4000),
  "GROUP_WRITE" VARCHAR(4000),
  "NODE_PATH" VARCHAR(4000),
  "MUSEUM_ID" INTEGER NOT NULL,
  PRIMARY KEY ("STORAGE_NODE_ID")
);

CREATE TABLE "MUSARK_STORAGE"."ROOM" (
  "STORAGE_NODE_ID" BIGINT NOT NULL,
  "PERIMETER_SECURITY" BOOLEAN,
  "THEFT_PROTECTION" BOOLEAN,
  "FIRE_PROTECTION" BOOLEAN,
  "WATER_DAMAGE_ASSESSMENT" BOOLEAN,
  "ROUTINES_AND_CONTINGENCY_PLAN" BOOLEAN,
  "RELATIVE_HUMIDITY" BOOLEAN,
  "TEMPERATURE_ASSESSMENT" BOOLEAN,
  "LIGHTING_CONDITION" BOOLEAN,
  "PREVENTIVE_CONSERVATION" BOOLEAN,
  PRIMARY KEY ("STORAGE_NODE_ID"),
  FOREIGN KEY ("STORAGE_NODE_ID") REFERENCES "MUSARK_STORAGE"."STORAGE_NODE"("STORAGE_NODE_ID")
);

CREATE TABLE "MUSARK_STORAGE"."BUILDING" (
  "STORAGE_NODE_ID" BIGINT NOT NULL,
  "POSTAL_ADDRESS" VARCHAR(512),
  PRIMARY KEY ("STORAGE_NODE_ID"),
  FOREIGN KEY ("STORAGE_NODE_ID") REFERENCES "MUSARK_STORAGE"."STORAGE_NODE"("STORAGE_NODE_ID")
);

CREATE TABLE "MUSARK_STORAGE"."ORGANISATION"(
  "STORAGE_NODE_ID" BIGINT NOT NULL,
  "POSTAL_ADDRESS"  VARCHAR(512),
  PRIMARY KEY ("STORAGE_NODE_ID"),
  FOREIGN KEY ("STORAGE_NODE_ID") REFERENCES "MUSARK_STORAGE"."STORAGE_NODE"("STORAGE_NODE_ID")
);

CREATE TABLE "MUSARK_STORAGE"."STORAGE_UNIT_LINK" (
  "LINK_ID" BIGSERIAL,
  "STORAGE_NODE_ID" BIGINT NOT NULL,
  "LINK" VARCHAR(255) NOT NULL,
  "RELATION" VARCHAR(100) NOT NULL,
  PRIMARY KEY ("LINK_ID"),
  FOREIGN KEY ("STORAGE_NODE_ID") REFERENCES "MUSARK_STORAGE"."STORAGE_NODE"("STORAGE_NODE_ID")
);

CREATE TABLE "MUSARK_STORAGE"."ROLE" (
  "ID" SERIAL,
  "NAME" VARCHAR(100) NOT NULL,
  "TYPE" VARCHAR(100),
  PRIMARY KEY ("ID")
);

CREATE TABLE "MUSARK_STORAGE"."EVENT_TYPE" (
  "ID" SERIAL,
  "NAME" VARCHAR(100) NOT NULL,
  PRIMARY KEY ("ID")
);

CREATE TABLE "MUSARK_STORAGE"."EVENT" (
  "ID" BIGSERIAL,
  "EVENT_TYPE_ID" INTEGER NOT NULL,
  "NOTE" VARCHAR(500),

  "EVENT_DATE" TIMESTAMP(0) NOT NULL,

  "REGISTERED_BY" VARCHAR(100) NOT NULL,
  "REGISTERED_DATE" TIMESTAMP NOT NULL,

  "VALUE_LONG" BIGINT,
  "VALUE_STRING" VARCHAR(250),
  "VALUE_FLOAT" DOUBLE PRECISION,

  "PART_OF" BIGINT,
  PRIMARY KEY ("ID"),
  FOREIGN KEY ("EVENT_TYPE_ID") REFERENCES "MUSARK_STORAGE"."EVENT_TYPE"("ID"),
  FOREIGN KEY ("PART_OF") REFERENCES "MUSARK_STORAGE"."EVENT"("ID")
);

-- ???
CREATE TABLE "MUSARK_STORAGE"."EVENT_RELATION_EVENT" (
  "FROM_EVENT_ID" BIGINT NOT NULL,
  "RELATION_ID" INTEGER NOT NULL,
  "TO_EVENT_ID" BIGINT NOT NULL,
  FOREIGN KEY ("FROM_EVENT_ID") REFERENCES "MUSARK_STORAGE"."EVENT"("ID"),
  FOREIGN KEY ("TO_EVENT_ID") REFERENCES "MUSARK_STORAGE"."EVENT"("ID")
);

CREATE TABLE "MUSARK_STORAGE"."LOCAL_OBJECT" (
  "OBJECT_ID" BIGSERIAL,
  "LATEST_MOVE_ID" BIGINT NOT NULL,
  "CURRENT_LOCATION_ID" BIGINT NOT NULL,
  "MUSEUM_ID" INTEGER NOT NULL,
  PRIMARY KEY ("OBJECT_ID")
);

CREATE TABLE "MUSARK_STORAGE"."EVENT_ROLE_ACTOR" (
  "EVENT_ID" BIGINT NOT NULL,
  "ROLE_ID" INTEGER NOT NULL,
  "ACTOR_ID" INTEGER NOT NULL,
  PRIMARY KEY ("EVENT_ID", "ROLE_ID", "ACTOR_ID"),
  FOREIGN KEY ("EVENT_ID") REFERENCES "MUSARK_STORAGE"."EVENT"("ID"),
  FOREIGN KEY ("ROLE_ID") REFERENCES "MUSARK_STORAGE"."ROLE"("ID")
);

CREATE TABLE "MUSARK_STORAGE"."EVENT_ROLE_OBJECT" (
  "EVENT_ID" BIGINT NOT NULL,
  "ROLE_ID" INTEGER NOT NULL,
  "OBJECT_ID" BIGINT NOT NULL,
  "EVENT_TYPE_ID" BIGINT NOT NULL,
  PRIMARY KEY ("EVENT_ID", "ROLE_ID", "OBJECT_ID"),
  FOREIGN KEY ("EVENT_ID") REFERENCES "MUSARK_STORAGE"."EVENT"("ID"),
  FOREIGN KEY ("ROLE_ID") REFERENCES "MUSARK_STORAGE"."ROLE"("ID"),
  FOREIGN KEY ("OBJECT_ID") REFERENCES "MUSARK_STORAGE"."LOCAL_OBJECT"("OBJECT_ID")
);

CREATE TABLE "MUSARK_STORAGE"."EVENT_ROLE_PLACE" (
  "EVENT_ID" BIGINT NOT NULL,
  "ROLE_ID" INTEGER NOT NULL,
  "PLACE_ID"  BIGINT NOT NULL,
  "EVENT_TYPE_ID" BIGINT NOT NULL,
  PRIMARY KEY ("EVENT_ID", "ROLE_ID", "PLACE_ID"),
  FOREIGN KEY ("EVENT_ID") REFERENCES "MUSARK_STORAGE"."EVENT"("ID"),
  FOREIGN KEY ("ROLE_ID") REFERENCES "MUSARK_STORAGE"."ROLE"("ID"),
  FOREIGN KEY ("PLACE_ID") REFERENCES "MUSARK_STORAGE"."STORAGE_NODE"("STORAGE_NODE_ID")
);

CREATE TABLE "MUSARK_STORAGE"."EVENT_ROLE_PLACE_AS_OBJECT" (
  "EVENT_ID" BIGINT NOT NULL,
  "ROLE_ID" INTEGER NOT NULL,
  "PLACE_ID"  BIGINT NOT NULL,
  "EVENT_TYPE_ID" BIGINT NOT NULL,
  PRIMARY KEY ("EVENT_ID", "ROLE_ID", "PLACE_ID"),
  FOREIGN KEY ("EVENT_ID") REFERENCES "MUSARK_STORAGE"."EVENT"("ID"),
  FOREIGN KEY ("ROLE_ID") REFERENCES "MUSARK_STORAGE"."ROLE"("ID"),
  FOREIGN KEY ("PLACE_ID") REFERENCES "MUSARK_STORAGE"."STORAGE_NODE"("STORAGE_NODE_ID")
);

CREATE TABLE "MUSARK_STORAGE"."OBSERVATION_FROM_TO" (
  "ID" BIGINT NOT NULL,
  "VALUE_FROM" DOUBLE PRECISION,
  "VALUE_TO" DOUBLE PRECISION,
  PRIMARY KEY ("ID"),
  FOREIGN KEY ("ID") REFERENCES "MUSARK_STORAGE"."EVENT"("ID")
);

CREATE TABLE "MUSARK_STORAGE"."E_ENVIRONMENT_REQUIREMENT" (
  "ID" BIGINT NOT NULL,
  "TEMPERATURE" DOUBLE PRECISION,
  "TEMP_TOLERANCE" INTEGER,
  "REL_HUMIDITY" DOUBLE PRECISION,
  "REL_HUM_TOLERANCE" INTEGER,
  "HYPOXIC_AIR" DOUBLE PRECISION,
  "HYP_AIR_TOLERANCE" INTEGER,
  "CLEANING" VARCHAR(250),
  "LIGHT" VARCHAR(250),
  PRIMARY KEY ("ID"),
  FOREIGN KEY ("ID") REFERENCES "MUSARK_STORAGE"."EVENT"("ID")
);

CREATE TABLE "MUSARK_STORAGE"."OBSERVATION_PEST_LIFECYCLE" (
  "EVENT_ID" BIGINT NOT NULL,
  "STAGE" VARCHAR(250),
  "QUANTITY" INTEGER,
  FOREIGN KEY ("EVENT_ID") REFERENCES "MUSARK_STORAGE"."EVENT"("ID")
);

CREATE TABLE "MUSARK_STORAGE"."URI_LINKS" (
  "ID" BIGSERIAL,
  "LOCAL_TABLE_ID" BIGINT NOT NULL,
  "REL" VARCHAR(255) NOT NULL,
  "HREF" VARCHAR(2000) NOT NULL,
  PRIMARY KEY ("ID")
);

CREATE SCHEMA IF NOT EXISTS "MUSIT_MAPPING";

CREATE TABLE "MUSIT_MAPPING"."VIEW_ACTOR" (
  "NY_ID" BIGSERIAL,
  "ACTORNAME" VARCHAR(512),
  "DATAPORTEN_ID" varchar(50),
  PRIMARY KEY ("NY_ID")
);

CREATE SCHEMA IF NOT EXISTS "MUSARK_ACTOR";

CREATE TABLE "MUSARK_ACTOR"."ORGANIZATION" (
  "ID" BIGSERIAL,
  "FN" VARCHAR(255) NOT NULL,
  "NICKNAME" VARCHAR(255),
  "TEL" VARCHAR(20),
  "WEB" VARCHAR(255),
  PRIMARY KEY ("ID")
);

CREATE TABLE "MUSARK_ACTOR"."ORGANIZATION_ADDRESS" (
  "ID" BIGSERIAL,
  "ORGANIZATION_ID" BIGINT NOT NULL,
  "TYPE" VARCHAR(20),
  "STREET_ADDRESS" VARCHAR(20),
  "LOCALITY" VARCHAR(255),
  "POSTAL_CODE" VARCHAR(12),
  "COUNTRY_NAME" VARCHAR(255),
  "LATITUDE" DOUBLE PRECISION,
  "LONGITUDE" DOUBLE PRECISION,
  PRIMARY KEY ("ID")
);

ALTER TABLE "MUSARK_ACTOR"."ORGANIZATION_ADDRESS" ADD FOREIGN KEY ("ORGANIZATION_ID") REFERENCES "MUSARK_ACTOR"."ORGANIZATION"("ID");

CREATE SCHEMA IF NOT EXISTS MUSIT_MAPPING;

CREATE TABLE "MUSIT_MAPPING"."VIEW_MUSITTHING" (
  "ID" BIGSERIAL,
  "DISPLAYID" VARCHAR NOT NULL,
  "DISPLAYNAME" VARCHAR
);

CREATE TABLE "MUSIT_MAPPING"."MUSITTHING" (
  "ID" BIGSERIAL,
  "MUSEUMNO" VARCHAR NOT NULL,
  "SUBNO" VARCHAR,
  "TERM" VARCHAR NOT NULL,
  "MUSEUMID" INTEGER NOT NULL,
  "MUSEUMNOASNUMBER" BIGINT,
  "SUBNOASNUMBER" BIGINT,
  PRIMARY KEY ("ID")
 );

SET search_path = "MUSARK_STORAGE", pg_catalog;

INSERT INTO "STORAGE_NODE" ("STORAGE_NODE_NAME", "AREA", "AREA_TO", "IS_STORAGE_UNIT", "IS_PART_OF", "HEIGHT", "HEIGHT_TO", "IS_DELETED", "STORAGE_TYPE", "GROUP_READ", "GROUP_WRITE", "NODE_PATH", "MUSEUM_ID") VALUES ('root-node', NULL, NULL, '1', NULL, NULL, NULL, false, 'Root', NULL, NULL, ',1,', 1);
INSERT INTO "STORAGE_NODE" ("STORAGE_NODE_NAME", "AREA", "AREA_TO", "IS_STORAGE_UNIT", "IS_PART_OF", "HEIGHT", "HEIGHT_TO", "IS_DELETED", "STORAGE_TYPE", "GROUP_READ", "GROUP_WRITE", "NODE_PATH", "MUSEUM_ID") VALUES ('Utviklingsmuseet', NULL, NULL, '1', 1, NULL, NULL, false, 'Organisation', NULL, NULL, ',1,2,', 1);
INSERT INTO "STORAGE_NODE" ("STORAGE_NODE_NAME", "AREA", "AREA_TO", "IS_STORAGE_UNIT", "IS_PART_OF", "HEIGHT", "HEIGHT_TO", "IS_DELETED", "STORAGE_TYPE", "GROUP_READ", "GROUP_WRITE", "NODE_PATH", "MUSEUM_ID") VALUES ('Forskningens hus', NULL, NULL, '1', 2, NULL, NULL, false, 'Building', NULL, NULL, ',1,2,3,', 1);
INSERT INTO "STORAGE_NODE" ("STORAGE_NODE_NAME", "AREA", "AREA_TO", "IS_STORAGE_UNIT", "IS_PART_OF", "HEIGHT", "HEIGHT_TO", "IS_DELETED", "STORAGE_TYPE", "GROUP_READ", "GROUP_WRITE", "NODE_PATH", "MUSEUM_ID") VALUES ('Kulturværelset', NULL, NULL, '1', 3, NULL, NULL, false, 'Room', NULL, NULL, ',1,2,3,4,', 1);
INSERT INTO "STORAGE_NODE" ("STORAGE_NODE_NAME", "AREA", "AREA_TO", "IS_STORAGE_UNIT", "IS_PART_OF", "HEIGHT", "HEIGHT_TO", "IS_DELETED", "STORAGE_TYPE", "GROUP_READ", "GROUP_WRITE", "NODE_PATH", "MUSEUM_ID") VALUES ('Naturværelset', NULL, NULL, '1', 3, NULL, NULL, false, 'Room', NULL, NULL, ',1,2,3,5,', 1);
INSERT INTO "STORAGE_NODE" ("STORAGE_NODE_NAME", "AREA", "AREA_TO", "IS_STORAGE_UNIT", "IS_PART_OF", "HEIGHT", "HEIGHT_TO", "IS_DELETED", "STORAGE_TYPE", "GROUP_READ", "GROUP_WRITE", "NODE_PATH", "MUSEUM_ID") VALUES ('Forskningsværelset', NULL, NULL, '1', 3, NULL, NULL, false, 'Room', NULL, NULL, ',1,2,3,6,', 1);

INSERT INTO "BUILDING" ("STORAGE_NODE_ID", "POSTAL_ADDRESS") VALUES (3, NULL);

INSERT INTO "EVENT_TYPE" ("NAME") VALUES ('MoveObject');
INSERT INTO "EVENT_TYPE" ("NAME") VALUES ('MovePlace');
INSERT INTO "EVENT_TYPE" ("NAME") VALUES ('EnvRequirement');
INSERT INTO "EVENT_TYPE" ("NAME") VALUES ('Control');
INSERT INTO "EVENT_TYPE" ("NAME") VALUES ('Observation');
INSERT INTO "EVENT_TYPE" ("NAME") VALUES ('ControlAlcohol');
INSERT INTO "EVENT_TYPE" ("NAME") VALUES ('ControlCleaning');
INSERT INTO "EVENT_TYPE" ("NAME") VALUES ('ControlGas');
INSERT INTO "EVENT_TYPE" ("NAME") VALUES ('ControlHypoxicAir');
INSERT INTO "EVENT_TYPE" ("NAME") VALUES ('ControlLightingCondition');
INSERT INTO "EVENT_TYPE" ("NAME") VALUES ('ControlMold');
INSERT INTO "EVENT_TYPE" ("NAME") VALUES ('ControlPest');
INSERT INTO "EVENT_TYPE" ("NAME") VALUES ('ControlRelativeHumidity');
INSERT INTO "EVENT_TYPE" ("NAME") VALUES ('ControlTemperature');
INSERT INTO "EVENT_TYPE" ("NAME") VALUES ('ObservationAlcohol');
INSERT INTO "EVENT_TYPE" ("NAME") VALUES ('ObservationCleaning');
INSERT INTO "EVENT_TYPE" ("NAME") VALUES ('ObservationFireProtection');
INSERT INTO "EVENT_TYPE" ("NAME") VALUES ('ObservationGas');
INSERT INTO "EVENT_TYPE" ("NAME") VALUES ('ObservationHypoxicAir');
INSERT INTO "EVENT_TYPE" ("NAME") VALUES ('ObservationLightingCondition');
INSERT INTO "EVENT_TYPE" ("NAME") VALUES ('ObservationMold');
INSERT INTO "EVENT_TYPE" ("NAME") VALUES ('ObservationPerimeterSecurity');
INSERT INTO "EVENT_TYPE" ("NAME") VALUES ('ObservationRelativeHumidity');
INSERT INTO "EVENT_TYPE" ("NAME") VALUES ('ObservationPest');
INSERT INTO "EVENT_TYPE" ("NAME") VALUES ('ObservationTemperature');
INSERT INTO "EVENT_TYPE" ("NAME") VALUES ('ObservationTheftProtection');
INSERT INTO "EVENT_TYPE" ("NAME") VALUES ('ObservationWaterDamageAssessment');

INSERT INTO "ROLE" ("NAME", "TYPE") VALUES ('DoneWith', 'object');
INSERT INTO "ROLE" ("NAME", "TYPE") VALUES ('DoneBy', 'actor');
INSERT INTO "ROLE" ("NAME", "TYPE") VALUES ('toPlace', 'storageNode');
INSERT INTO "ROLE" ("NAME", "TYPE") VALUES ('fromPlace', 'storageNode');

INSERT INTO "LOCAL_OBJECT" ("LATEST_MOVE_ID", "CURRENT_LOCATION_ID", "MUSEUM_ID") VALUES (9999, 4, 1);
INSERT INTO "LOCAL_OBJECT" ("LATEST_MOVE_ID", "CURRENT_LOCATION_ID", "MUSEUM_ID") VALUES (9999, 4, 1);
INSERT INTO "LOCAL_OBJECT" ("LATEST_MOVE_ID", "CURRENT_LOCATION_ID", "MUSEUM_ID") VALUES (9999, 4, 1);
INSERT INTO "LOCAL_OBJECT" ("LATEST_MOVE_ID", "CURRENT_LOCATION_ID", "MUSEUM_ID") VALUES (9999, 4, 1);
INSERT INTO "LOCAL_OBJECT" ("LATEST_MOVE_ID", "CURRENT_LOCATION_ID", "MUSEUM_ID") VALUES (9999, 5, 1);
INSERT INTO "LOCAL_OBJECT" ("LATEST_MOVE_ID", "CURRENT_LOCATION_ID", "MUSEUM_ID") VALUES (9999, 5, 1);
INSERT INTO "LOCAL_OBJECT" ("LATEST_MOVE_ID", "CURRENT_LOCATION_ID", "MUSEUM_ID") VALUES (9999, 5, 1);
INSERT INTO "LOCAL_OBJECT" ("LATEST_MOVE_ID", "CURRENT_LOCATION_ID", "MUSEUM_ID") VALUES (9999, 5, 1);
INSERT INTO "LOCAL_OBJECT" ("LATEST_MOVE_ID", "CURRENT_LOCATION_ID", "MUSEUM_ID") VALUES (9999, 5, 1);
INSERT INTO "LOCAL_OBJECT" ("LATEST_MOVE_ID", "CURRENT_LOCATION_ID", "MUSEUM_ID") VALUES (9999, 6, 1);
INSERT INTO "LOCAL_OBJECT" ("LATEST_MOVE_ID", "CURRENT_LOCATION_ID", "MUSEUM_ID") VALUES (9999, 6, 1);
INSERT INTO "LOCAL_OBJECT" ("LATEST_MOVE_ID", "CURRENT_LOCATION_ID", "MUSEUM_ID") VALUES (9999, 6, 1);
INSERT INTO "LOCAL_OBJECT" ("LATEST_MOVE_ID", "CURRENT_LOCATION_ID", "MUSEUM_ID") VALUES (9999, 6, 1);

INSERT INTO "ORGANISATION" ("STORAGE_NODE_ID", "POSTAL_ADDRESS") VALUES (2, NULL);

INSERT INTO "ROOM" ("STORAGE_NODE_ID", "PERIMETER_SECURITY", "THEFT_PROTECTION", "FIRE_PROTECTION", "WATER_DAMAGE_ASSESSMENT", "ROUTINES_AND_CONTINGENCY_PLAN", "RELATIVE_HUMIDITY", "TEMPERATURE_ASSESSMENT", "LIGHTING_CONDITION", "PREVENTIVE_CONSERVATION") VALUES (4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "ROOM" ("STORAGE_NODE_ID", "PERIMETER_SECURITY", "THEFT_PROTECTION", "FIRE_PROTECTION", "WATER_DAMAGE_ASSESSMENT", "ROUTINES_AND_CONTINGENCY_PLAN", "RELATIVE_HUMIDITY", "TEMPERATURE_ASSESSMENT", "LIGHTING_CONDITION", "PREVENTIVE_CONSERVATION") VALUES (5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "ROOM" ("STORAGE_NODE_ID", "PERIMETER_SECURITY", "THEFT_PROTECTION", "FIRE_PROTECTION", "WATER_DAMAGE_ASSESSMENT", "ROUTINES_AND_CONTINGENCY_PLAN", "RELATIVE_HUMIDITY", "TEMPERATURE_ASSESSMENT", "LIGHTING_CONDITION", "PREVENTIVE_CONSERVATION") VALUES (6, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

SET search_path = "MUSIT_MAPPING", pg_catalog;

INSERT INTO "VIEW_ACTOR" ("ACTORNAME", "DATAPORTEN_ID") VALUES ('Jarle Stabell', 'jarle');

INSERT INTO "VIEW_MUSITTHING" ("DISPLAYID", "DISPLAYNAME") VALUES ('MusK58/1', 'Rar dings');
INSERT INTO "VIEW_MUSITTHING" ("DISPLAYID", "DISPLAYNAME") VALUES ('MusK58/2', 'Mansjettknapp');
INSERT INTO "VIEW_MUSITTHING" ("DISPLAYID", "DISPLAYNAME") VALUES ('MusK58/3', 'Spenne');
INSERT INTO "VIEW_MUSITTHING" ("DISPLAYID", "DISPLAYNAME") VALUES ('MusK58/4', 'Briller');
INSERT INTO "VIEW_MUSITTHING" ("DISPLAYID", "DISPLAYNAME") VALUES ('MusN36/1', 'Husflue');
INSERT INTO "VIEW_MUSITTHING" ("DISPLAYID", "DISPLAYNAME") VALUES ('MusN45', 'Dyngebille');
INSERT INTO "VIEW_MUSITTHING" ("DISPLAYID", "DISPLAYNAME") VALUES ('MusN36/2', 'Spyflue');
INSERT INTO "VIEW_MUSITTHING" ("DISPLAYID", "DISPLAYNAME") VALUES ('MusN37', 'Bendelorm');
INSERT INTO "VIEW_MUSITTHING" ("DISPLAYID", "DISPLAYNAME") VALUES ('MusN28', 'Tusenben');
INSERT INTO "VIEW_MUSITTHING" ("DISPLAYID", "DISPLAYNAME") VALUES ('MusK400', 'Brynje');
INSERT INTO "VIEW_MUSITTHING" ("DISPLAYID", "DISPLAYNAME") VALUES ('MusN337', 'Sommerfulgvinge');
INSERT INTO "VIEW_MUSITTHING" ("DISPLAYID", "DISPLAYNAME") VALUES ('MusN77', 'Lavastein');
INSERT INTO "VIEW_MUSITTHING" ("DISPLAYID", "DISPLAYNAME") VALUES ('MusK43', 'Krakk');