export loadInfo from './load-info'
export loadAuth from './load-auth'
export login from './login'
export logout from './logout'
export loadLanguage from './load-language'
export * as widget from './widget/index'
